const RARITIES = {
  white:   { name: '白卡',   order: 0, color: '#9ca3af', weight: 55,      basePower: 1,       frag: 1 },
green:   { name: '绿卡',   order: 1, color: '#16a34a', weight: 7.3,     basePower: 10,      frag: 3 },
  blue:    { name: '蓝卡',   order: 2, color: '#2563eb', weight: 2.5,     basePower: 20,      frag: 105 },
  purple:  { name: '紫卡',   order: 3, color: '#7c3aed', weight: 0.5,     basePower: 45,      frag: 541 },
  gold:    { name: '金卡',   order: 4, color: '#d97706', weight: 0.1,     basePower: 107,     frag: 3141 },
  red:     { name: '红卡',   order: 5, color: '#dc2626', weight: 0.004,    basePower: 12000,   frag: 79374 },
  black:   { name: '黑卡',   order: 6, color: '#111827', weight: 0.0001,  basePower: 80000,   frag: 2725172 },
  rainbow: { name: '炫彩卡', order: 7, color: 'rainbow', weight: 0.00002, basePower: 2000000, frag: 16351030 },
};

const RARITY_LIST = Object.keys(RARITIES).map(k => ({ id: k, ...RARITIES[k] })).sort((a, b) => a.order - b.order);

const CARDS = [
  { id: 'egg-rainbow',  name: '炫彩蛋',     rarity: 'white',  start: true, unique: true, art: { type: 'egg', colors: 'rainbow' },               desc: '传说中集齐五种元素之蛋才会孵化的神奇蛋。',                flavor: '它只是一颗白卡蛋，但梦想是炫彩的。',             formation: ['egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'egg-gold',     name: '金蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ffe9a8', '#f5b52e'] },  desc: '沉甸甸的蛋，隐约透出金光。',                              flavor: '晃一晃，里面有叮当声。',                        formation: [] },
  { id: 'egg-wood',     name: '木蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#e0d3b0', '#8a6b3f'] },  desc: '外壳带着树皮纹路的蛋。',                                  flavor: '插进土里好像会发芽。',                          formation: [] },
  { id: 'egg-water',    name: '水蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#d6ecff', '#4da3ff'] },  desc: '轻轻晃动，能听到水声的蛋。',                              flavor: '永远潮乎乎的。',                                formation: [] },
  { id: 'egg-fire',     name: '火蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ffe0cc', '#ff7a45'] },  desc: '摸上去热乎乎的蛋。',                                      flavor: '冬天抱着它睡觉。',                              formation: [] },
  { id: 'egg-earth',    name: '土蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ecd9b8', '#96704a'] },  desc: '沾着泥土气息的蛋。',                                      flavor: '重得像个哑铃。',                                formation: [] },
  { id: 'sapling',      name: '小树苗',     rarity: 'green',  art: { type: 'emoji', emoji: '🌱' },  desc: '需要三颗蛋的陪伴才能茁壮成长。',            flavor: '一天长一片叶子。',                              formation: ['egg-wood', 'egg-earth', 'egg-water'] },
  { id: 'ember',        name: '小火苗',     rarity: 'green',  art: { type: 'emoji', emoji: '🔥' },  desc: '一点就着的小脾气。',                        flavor: '吹口气就会灭。',                              formation: ['egg-fire', 'egg-wood', 'egg-gold'] },
  { id: 'droplet',      name: '小水灵',     rarity: 'green',  art: { type: 'emoji', emoji: '💧' },  desc: '整天咕嘟咕嘟冒泡。',                        flavor: '哭的时候会下雨。',                            formation: ['egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'forest-guard', name: '森林守卫',   rarity: 'blue',   art: { type: 'emoji', emoji: '🌳' },  desc: '森林里最可靠的伙伴。',                      flavor: '每一片叶子都在放哨。',                        formation: ['sapling', 'egg-wood', 'egg-earth'] },
  { id: 'lava-turtle',  name: '岩浆龟',     rarity: 'blue',   art: { type: 'emoji', emoji: '🐢' },  desc: '龟壳里住着一座小火山。',                    flavor: '走得慢，但挡不住。',                          formation: ['ember', 'egg-fire'] },
  { id: 'elementalist', name: '元素使',     rarity: 'purple', art: { type: 'emoji', emoji: '⚗️' },  desc: '调和水火木土的大师。',                      flavor: '配方是机密。',                                formation: ['egg-fire', 'egg-water', 'egg-wood', 'egg-earth'] },
  { id: 'rainbow-dragon', name: '彩虹龙',   rarity: 'gold',   art: { type: 'emoji', emoji: '🐉' },  desc: '横跨天际的传说之龙。',                      flavor: '它飞过的地方会下糖果雨。',                  formation: ['elementalist', 'forest-guard', 'lava-turtle', 'ember', 'droplet', 'sapling'] },
  { id: 'chaos-lord',   name: '混沌魔王',   rarity: 'red',    art: { type: 'emoji', emoji: '👹' },  desc: '吞噬光明与秩序。',                          flavor: '连影子都害怕它。',                            formation: ['rainbow-dragon', 'elementalist', 'egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'abyss-lord',   name: '深渊之主',   rarity: 'black',  art: { type: 'emoji', emoji: '🕳️' },  desc: '凝视深渊者，终将被深渊凝视。',              flavor: '没人见过它的真面目。',                        formation: ['chaos-lord', 'rainbow-dragon', 'elementalist', 'egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'creator',      name: '创世神',     rarity: 'rainbow', art: { type: 'emoji', emoji: '✨' },  desc: '一切卡片的起源。',                          flavor: '它给自己写的登场台词。',                      formation: ['abyss-lord', 'chaos-lord', 'rainbow-dragon', 'elementalist'] },
  { id: 'egg-stone',    name: '石头蛋',     rarity: 'white',  art: { type: 'egg', colors: ['#e2e8f0', '#94a3b8'] },  desc: '重得像块石头的蛋。',                      flavor: '砸核桃挺好用。',                          formation: [] },
  { id: 'egg-thunder',  name: '雷蛋',       rarity: 'white',  art: { type: 'egg', colors: ['#fef9c3', '#eab308'] },  desc: '偶尔会噼啪作响的蛋。',                    flavor: '摸之前记得先洗手。',                      formation: [] },
  { id: 'egg-ice',      name: '冰蛋',       rarity: 'white',  art: { type: 'egg', colors: ['#e0f2fe', '#38bdf8'] },  desc: '摸起来凉飕飕的蛋。',                      flavor: '夏天想抱着它。',                          formation: [] },
  { id: 'rockling',     name: '小石头',     rarity: 'green',  art: { type: 'emoji', emoji: '🪨' },  desc: '一块会滚的小石头。',                      flavor: '滚起来比看起来快。',                      formation: ['egg-stone', 'egg-gold', 'egg-wood'] },
  { id: 'cloudling',    name: '小云朵',     rarity: 'green',  art: { type: 'emoji', emoji: '☁️' },  desc: '软绵绵的云朵精灵。',                      flavor: '心情好就下雨。',                          formation: ['egg-water', 'egg-thunder', 'egg-ice'] },
  { id: 'blossom',      name: '小花精',     rarity: 'green',  art: { type: 'emoji', emoji: '🌸' },  desc: '从花苞里钻出来的小家伙。',                flavor: '走到哪香到哪。',                          formation: ['egg-wood', 'egg-water', 'egg-earth'] },
  { id: 'thunder-spirit', name: '雷灵',     rarity: 'blue',   art: { type: 'emoji', emoji: '⚡' },  desc: '脾气火爆的电系精灵。',                    flavor: '打雷天最精神。',                          formation: ['cloudling', 'egg-thunder', 'egg-water'] },
  { id: 'ice-wisp',     name: '冰灵',       rarity: 'blue',   art: { type: 'emoji', emoji: '❄️' },  desc: '指尖掠过霜雪的精灵。',                    flavor: '夏天站在它身边很凉快。',                  formation: ['blossom', 'egg-ice', 'egg-wood'] },
  { id: 'rock-golem',   name: '岩甲兵',     rarity: 'blue',   art: { type: 'emoji', emoji: '🗿' },  desc: '岩石堆成的沉默士兵。',                    flavor: '它的笑点很低。',                          formation: ['rockling', 'egg-earth', 'egg-gold'] },
  { id: 'storm-witch',  name: '风暴女巫',   rarity: 'purple', art: { type: 'emoji', emoji: '🧙' },  desc: '把闪电装进帽子的女巫。',                  flavor: '帽子其实是晴雨计。',                      formation: ['thunder-spirit', 'cloudling', 'egg-thunder', 'egg-ice'] },
  { id: 'crystal-golem', name: '水晶魔像',  rarity: 'purple', art: { type: 'emoji', emoji: '💎' },  desc: '浑身剔透的水晶造物。',                    flavor: '在阳光下会闪瞎眼。',                      formation: ['rock-golem', 'ice-wisp', 'egg-ice', 'egg-gold'] },
  { id: 'thunder-dragon', name: '雷光龙',   rarity: 'gold',   art: { type: 'emoji', emoji: '🐲' },  desc: '御雷而行的东方之龙。',                    flavor: '尾巴一甩就是一道闪电。',                  formation: ['storm-witch', 'thunder-spirit', 'cloudling', 'ice-wisp', 'egg-thunder', 'egg-ice'] },
  { id: 'gold-golem',   name: '金晶王',     rarity: 'gold',   art: { type: 'emoji', emoji: '👑' },  desc: '统治矿物王国的黄金之王。',                flavor: '它的王座是块大金矿。',                    formation: ['crystal-golem', 'rock-golem', 'rockling', 'egg-gold', 'egg-wood', 'egg-earth'] },
  { id: 'storm-lord',   name: '风暴之主',   rarity: 'red',    art: { type: 'emoji', emoji: '🌩️' },  desc: '将整片天空握在手中。',                    flavor: '它一打喷嚏就会刮台风。',                  formation: ['thunder-dragon', 'storm-witch', 'gold-golem', 'egg-thunder', 'egg-gold'] },
  { id: 'void-dragon',  name: '虚空之龙',   rarity: 'black',  art: { type: 'emoji', emoji: '🌀' },  desc: '蛰伏于虚空尽头的古龙。',                  flavor: '它的叹息就是黑洞。',                      formation: ['storm-lord', 'thunder-dragon', 'gold-golem', 'crystal-golem', 'egg-thunder', 'egg-ice'] },
  { id: 'green-01', name: '碧使', rarity: 'green', art: { type: 'emoji', emoji: '🕯️' }, desc: '在田野间欢快蹦跳。', flavor: '别踩到它的尾巴。', formation: ['sapling', 'ember', 'blossom'] },
  { id: 'green-02', name: '蒲学徒', rarity: 'green', art: { type: 'emoji', emoji: '🌌' }, desc: '爱在晨露里打滚。', flavor: '它觉得自己最可爱。', formation: ['cloudling', 'blossom'] },
  { id: 'green-03', name: '柳使', rarity: 'green', art: { type: 'emoji', emoji: '🍄' }, desc: '和同伴挤在一起晒太阳。', flavor: '它觉得自己最可爱。', formation: ['rockling', 'green-01', 'ember'] },
  { id: 'green-04', name: '蔓仆', rarity: 'green', art: { type: 'emoji', emoji: '🍀' }, desc: '和同伴挤在一起晒太阳。', flavor: '别踩到它的尾巴。', formation: ['green-03', 'blossom'] },
  { id: 'green-05', name: '果精灵', rarity: 'green', art: { type: 'emoji', emoji: '🐺' }, desc: '春天最先醒来的小东西。', flavor: '它觉得自己最可爱。', formation: ['blossom', 'rockling'] },
  { id: 'green-06', name: '芽仆', rarity: 'green', art: { type: 'emoji', emoji: '🦁' }, desc: '在田野间欢快蹦跳。', flavor: '今天也在努力长大。', formation: ['rockling', 'green-02', 'blossom'] },
  { id: 'green-07', name: '芽芽', rarity: 'green', art: { type: 'emoji', emoji: '🧬' }, desc: '爱在晨露里打滚。', flavor: '它觉得自己最可爱。', formation: ['sapling', 'cloudling', 'green-04'] },
  { id: 'green-08', name: '苔童', rarity: 'green', art: { type: 'emoji', emoji: '🐟' }, desc: '爱在晨露里打滚。', flavor: '它觉得自己最可爱。', formation: ['green-01', 'green-05', 'sapling'] },
  { id: 'green-09', name: '蔓芽', rarity: 'green', art: { type: 'emoji', emoji: '🌋' }, desc: '爱在晨露里打滚。', flavor: '别踩到它的尾巴。', formation: ['sapling', 'green-03'] },
  { id: 'green-10', name: '竹祭司', rarity: 'green', art: { type: 'emoji', emoji: '🐏' }, desc: '在田野间欢快蹦跳。', flavor: '今天也在努力长大。', formation: ['blossom', 'droplet', 'green-05'] },
  { id: 'green-11', name: '松族', rarity: 'green', art: { type: 'emoji', emoji: '🪙' }, desc: '和同伴挤在一起晒太阳。', flavor: '今天也在努力长大。', formation: ['green-02', 'blossom', 'droplet'] },
  { id: 'green-12', name: '青卫', rarity: 'green', art: { type: 'emoji', emoji: '🦊' }, desc: '春天最先醒来的小东西。', flavor: '它觉得自己最可爱。', formation: ['green-11', 'green-06'] },
  { id: 'green-13', name: '苍卫', rarity: 'green', art: { type: 'emoji', emoji: '🪱' }, desc: '春天最先醒来的小东西。', flavor: '它觉得自己最可爱。', formation: ['green-06', 'ember', 'cloudling'] },
  { id: 'green-14', name: '竹姬', rarity: 'green', art: { type: 'emoji', emoji: '🫀' }, desc: '爱在晨露里打滚。', flavor: '今天也在努力长大。', formation: ['green-02', 'green-04', 'cloudling'] },
  { id: 'green-15', name: '苔姬', rarity: 'green', art: { type: 'emoji', emoji: '☄️' }, desc: '春天最先醒来的小东西。', flavor: '今天也在努力长大。', formation: ['ember', 'green-12', 'cloudling'] },
  { id: 'green-16', name: '蒲祭司', rarity: 'green', art: { type: 'emoji', emoji: '🧭' }, desc: '在田野间欢快蹦跳。', flavor: '今天也在努力长大。', formation: ['green-04', 'green-05', 'green-12'] },
  { id: 'blue-01', name: '泉灵', rarity: 'blue', art: { type: 'emoji', emoji: '🧿' }, desc: '把潮汐当作摇篮。', flavor: '心里装着整片海。', formation: ['thunder-spirit', 'lava-turtle', 'sapling'] },
  { id: 'blue-02', name: '雾士', rarity: 'blue', art: { type: 'emoji', emoji: '🐤' }, desc: '栖息在溪流与湖畔。', flavor: '心里装着整片海。', formation: ['lava-turtle', 'sapling'] },
  { id: 'blue-03', name: '雪灵', rarity: 'blue', art: { type: 'emoji', emoji: '🐬' }, desc: '把潮汐当作摇篮。', flavor: '偶尔也想要一个拥抱。', formation: ['blue-01', 'rockling'] },
  { id: 'blue-04', name: '澜使', rarity: 'blue', art: { type: 'emoji', emoji: '🪂' }, desc: '栖息在溪流与湖畔。', flavor: '心里装着整片海。', formation: ['blue-03', 'blossom'] },
  { id: 'blue-05', name: '澜龙', rarity: 'blue', art: { type: 'emoji', emoji: '🐕' }, desc: '栖息在溪流与湖畔。', flavor: '偶尔也想要一个拥抱。', formation: ['thunder-spirit', 'blue-04', 'rockling', 'blossom'] },
  { id: 'blue-06', name: '湖蟹', rarity: 'blue', art: { type: 'emoji', emoji: '🐙' }, desc: '雨天格外活泼。', flavor: '心里装着整片海。', formation: ['blue-04', 'blue-01', 'droplet'] },
  { id: 'blue-07', name: '波精', rarity: 'blue', art: { type: 'emoji', emoji: '🧲' }, desc: '把潮汐当作摇篮。', flavor: '偶尔也想要一个拥抱。', formation: ['blue-04', 'ice-wisp', 'sapling'] },
  { id: 'blue-08', name: '雪卫', rarity: 'blue', art: { type: 'emoji', emoji: '🐼' }, desc: '栖息在溪流与湖畔。', flavor: '偶尔也想要一个拥抱。', formation: ['blue-07', 'ember', 'droplet'] },
  { id: 'blue-09', name: '冰兽', rarity: 'blue', art: { type: 'emoji', emoji: '🐚' }, desc: '把潮汐当作摇篮。', flavor: '打湿裤脚是它的恶作剧。', formation: ['blue-06', 'ember'] },
  { id: 'blue-10', name: '瀑使', rarity: 'blue', art: { type: 'emoji', emoji: '🐯' }, desc: '把潮汐当作摇篮。', flavor: '心里装着整片海。', formation: ['blue-01', 'blue-03', 'cloudling', 'droplet'] },
  { id: 'blue-11', name: '波师', rarity: 'blue', art: { type: 'emoji', emoji: '🦠' }, desc: '栖息在溪流与湖畔。', flavor: '心里装着整片海。', formation: ['forest-guard', 'rock-golem', 'sapling'] },
  { id: 'blue-12', name: '湖鲸', rarity: 'blue', art: { type: 'emoji', emoji: '🛠️' }, desc: '驭水而行的精灵。', flavor: '心里装着整片海。', formation: ['blue-03', 'blue-05', 'ember'] },
  { id: 'blue-13', name: '澜兽', rarity: 'blue', art: { type: 'emoji', emoji: '🦌' }, desc: '栖息在溪流与湖畔。', flavor: '心里装着整片海。', formation: ['lava-turtle', 'rockling', 'sapling'] },
  { id: 'blue-14', name: '渊龙', rarity: 'blue', art: { type: 'emoji', emoji: '🦀' }, desc: '雨天格外活泼。', flavor: '偶尔也想要一个拥抱。', formation: ['blue-10', 'blue-05', 'rockling', 'sapling'] },
  { id: 'blue-15', name: '湖士', rarity: 'blue', art: { type: 'emoji', emoji: '🐡' }, desc: '栖息在溪流与湖畔。', flavor: '心里装着整片海。', formation: ['blue-13', 'blue-08', 'ember', 'droplet'] },
  { id: 'blue-16', name: '瀑鲛', rarity: 'blue', art: { type: 'emoji', emoji: '⚒️' }, desc: '栖息在溪流与湖畔。', flavor: '心里装着整片海。', formation: ['lava-turtle', 'ember', 'rockling'] },
  { id: 'purple-01', name: '魅将', rarity: 'purple', art: { type: 'emoji', emoji: '🧜' }, desc: '掌握隐秘的奥术。', flavor: '它念咒语时会眯眼睛。', formation: ['storm-witch', 'elementalist', 'lava-turtle'] },
  { id: 'purple-02', name: '辰伯爵', rarity: 'purple', art: { type: 'emoji', emoji: '🦨' }, desc: '古老的咒语信手拈来。', flavor: '其实怕打雷。', formation: ['storm-witch', 'purple-01', 'forest-guard', 'ice-wisp'] },
  { id: 'purple-03', name: '星术士', rarity: 'purple', art: { type: 'emoji', emoji: '🧺' }, desc: '掌握隐秘的奥术。', flavor: '它念咒语时会眯眼睛。', formation: ['purple-01', 'forest-guard'] },
  { id: 'purple-04', name: '魅伯爵', rarity: 'purple', art: { type: 'emoji', emoji: '🦾' }, desc: '举手投足暗藏魔力。', flavor: '月圆之夜格外精神。', formation: ['crystal-golem', 'purple-03', 'rock-golem', 'thunder-spirit'] },
  { id: 'purple-05', name: '影术士', rarity: 'purple', art: { type: 'emoji', emoji: '🗡️' }, desc: '古老的咒语信手拈来。', flavor: '其实怕打雷。', formation: ['purple-02', 'purple-03', 'lava-turtle'] },
  { id: 'purple-06', name: '夜爵', rarity: 'purple', art: { type: 'emoji', emoji: '🦎' }, desc: '掌握隐秘的奥术。', flavor: '月圆之夜格外精神。', formation: ['crystal-golem', 'purple-02', 'forest-guard'] },
  { id: 'purple-07', name: '梦巫师', rarity: 'purple', art: { type: 'emoji', emoji: '🐑' }, desc: '在月光下修行。', flavor: '其实怕打雷。', formation: ['purple-02', 'ice-wisp'] },
  { id: 'purple-08', name: '冥侯', rarity: 'purple', art: { type: 'emoji', emoji: '🪓' }, desc: '掌握隐秘的奥术。', flavor: '月圆之夜格外精神。', formation: ['purple-04', 'ice-wisp'] },
  { id: 'purple-09', name: '月巫师', rarity: 'purple', art: { type: 'emoji', emoji: '🐸' }, desc: '举手投足暗藏魔力。', flavor: '它念咒语时会眯眼睛。', formation: ['purple-04', 'ice-wisp', 'rock-golem'] },
  { id: 'purple-10', name: '月爵', rarity: 'purple', art: { type: 'emoji', emoji: '🧝' }, desc: '掌握隐秘的奥术。', flavor: '月圆之夜格外精神。', formation: ['storm-witch', 'lava-turtle'] },
  { id: 'purple-11', name: '夜将', rarity: 'purple', art: { type: 'emoji', emoji: '🌿' }, desc: '在月光下修行。', flavor: '其实怕打雷。', formation: ['purple-07', 'ice-wisp', 'rock-golem'] },
  { id: 'purple-12', name: '夜司祭', rarity: 'purple', art: { type: 'emoji', emoji: '🐳' }, desc: '举手投足暗藏魔力。', flavor: '月圆之夜格外精神。', formation: ['purple-05', 'purple-09', 'lava-turtle'] },
  { id: 'purple-13', name: '辰爵', rarity: 'purple', art: { type: 'emoji', emoji: '🐻' }, desc: '在月光下修行。', flavor: '月圆之夜格外精神。', formation: ['purple-03', 'forest-guard'] },
  { id: 'purple-14', name: '暮侯', rarity: 'purple', art: { type: 'emoji', emoji: '🪶' }, desc: '举手投足暗藏魔力。', flavor: '它念咒语时会眯眼睛。', formation: ['purple-02', 'purple-05', 'ice-wisp'] },
  { id: 'purple-15', name: '暮骑', rarity: 'purple', art: { type: 'emoji', emoji: '🦢' }, desc: '举手投足暗藏魔力。', flavor: '其实怕打雷。', formation: ['purple-14', 'thunder-spirit'] },
  { id: 'purple-16', name: '夜祭司', rarity: 'purple', art: { type: 'emoji', emoji: '⭐' }, desc: '在月光下修行。', flavor: '它念咒语时会眯眼睛。', formation: ['storm-witch', 'purple-06', 'rock-golem', 'thunder-spirit'] },
  { id: 'gold-01', name: '冠爵', rarity: 'gold', art: { type: 'emoji', emoji: '⛏️' }, desc: '呼风唤雨的王者。', flavor: '王冠其实很重。', formation: ['thunder-dragon', 'crystal-golem'] },
  { id: 'gold-02', name: '虎王', rarity: 'gold', art: { type: 'emoji', emoji: '🏺' }, desc: '身披荣光的传说。', flavor: '它吃早餐也要摆架势。', formation: ['thunder-dragon', 'elementalist', 'crystal-golem'] },
  { id: 'gold-03', name: '鸾宰相', rarity: 'gold', art: { type: 'emoji', emoji: '⚗️' }, desc: '身披荣光的传说。', flavor: '王冠其实很重。', formation: ['gold-golem', 'storm-witch', 'elementalist'] },
  { id: 'gold-04', name: '君元帅', rarity: 'gold', art: { type: 'emoji', emoji: '⚜️' }, desc: '身披荣光的传说。', flavor: '脾气比传说温和。', formation: ['gold-02', 'rainbow-dragon', 'storm-witch'] },
  { id: 'gold-05', name: '豹爵', rarity: 'gold', art: { type: 'emoji', emoji: '🌇' }, desc: '呼风唤雨的王者。', flavor: '脾气比传说温和。', formation: ['gold-golem', 'elementalist', 'storm-witch'] },
  { id: 'gold-06', name: '鹤将军', rarity: 'gold', art: { type: 'emoji', emoji: '🦒' }, desc: '坐镇一方国度的强者。', flavor: '王冠其实很重。', formation: ['gold-05', 'gold-golem', 'storm-witch'] },
  { id: 'gold-07', name: '贤元帅', rarity: 'gold', art: { type: 'emoji', emoji: '🗿' }, desc: '呼风唤雨的王者。', flavor: '脾气比传说温和。', formation: ['gold-01', 'gold-02', 'elementalist', 'crystal-golem'] },
  { id: 'gold-08', name: '鹤王', rarity: 'gold', art: { type: 'emoji', emoji: '🩸' }, desc: '让大地为之震颤。', flavor: '脾气比传说温和。', formation: ['gold-05', 'rainbow-dragon', 'crystal-golem', 'storm-witch'] },
  { id: 'gold-09', name: '鸾元帅', rarity: 'gold', art: { type: 'emoji', emoji: '🌟' }, desc: '呼风唤雨的王者。', flavor: '它吃早餐也要摆架势。', formation: ['gold-04', 'gold-07', 'storm-witch'] },
  { id: 'gold-10', name: '麟预言家', rarity: 'gold', art: { type: 'emoji', emoji: '🌊' }, desc: '让大地为之震颤。', flavor: '王冠其实很重。', formation: ['gold-05', 'elementalist'] },
  { id: 'gold-11', name: '豹君主', rarity: 'gold', art: { type: 'emoji', emoji: '🦐' }, desc: '呼风唤雨的王者。', flavor: '王冠其实很重。', formation: ['thunder-dragon', 'elementalist'] },
  { id: 'gold-12', name: '麟宰相', rarity: 'gold', art: { type: 'emoji', emoji: '🌷' }, desc: '身披荣光的传说。', flavor: '王冠其实很重。', formation: ['thunder-dragon', 'gold-01', 'elementalist', 'storm-witch'] },
  { id: 'gold-13', name: '冠预言家', rarity: 'gold', art: { type: 'emoji', emoji: '🪐' }, desc: '坐镇一方国度的强者。', flavor: '它吃早餐也要摆架势。', formation: ['rainbow-dragon', 'gold-golem', 'elementalist', 'storm-witch'] },
  { id: 'gold-14', name: '傲祭司', rarity: 'gold', art: { type: 'emoji', emoji: '🐄' }, desc: '身披荣光的传说。', flavor: '脾气比传说温和。', formation: ['gold-10', 'gold-13', 'crystal-golem'] },
  { id: 'gold-15', name: '权宰相', rarity: 'gold', art: { type: 'emoji', emoji: '💎' }, desc: '呼风唤雨的王者。', flavor: '它吃早餐也要摆架势。', formation: ['thunder-dragon', 'storm-witch', 'elementalist'] },
  { id: 'gold-16', name: '皇骑士长', rarity: 'gold', art: { type: 'emoji', emoji: '🔮' }, desc: '坐镇一方国度的强者。', flavor: '王冠其实很重。', formation: ['gold-03', 'crystal-golem', 'storm-witch'] },
  { id: 'red-01', name: '魔尊', rarity: 'red', art: { type: 'emoji', emoji: '🪄' }, desc: '令人闻风丧胆的存在。', flavor: '脾气和名字一样爆。', formation: ['chaos-lord', 'storm-lord', 'gold-golem', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-02', name: '焚魔王', rarity: 'red', art: { type: 'emoji', emoji: '⚱️' }, desc: '令人闻风丧胆的存在。', flavor: '它跺跺脚，世界抖三抖。', formation: ['chaos-lord', 'storm-lord', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-03', name: '蚀主', rarity: 'red', art: { type: 'emoji', emoji: '🤖' }, desc: '以毁灭为乐。', flavor: '它跺跺脚，世界抖三抖。', formation: ['storm-lord', 'red-02', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-04', name: '灭帝', rarity: 'red', art: { type: 'emoji', emoji: '🦘' }, desc: '以毁灭为乐。', flavor: '脾气和名字一样爆。', formation: ['red-01', 'storm-lord', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-05', name: '厄暴君', rarity: 'red', art: { type: 'emoji', emoji: '👽' }, desc: '令人闻风丧胆的存在。', flavor: '脾气和名字一样爆。', formation: ['storm-lord', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-06', name: '邪收割者', rarity: 'red', art: { type: 'emoji', emoji: '🌅' }, desc: '吞噬一切的天灾。', flavor: '据说它笑过两次。', formation: ['red-05', 'red-03', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-07', name: '血吞噬者', rarity: 'red', art: { type: 'emoji', emoji: '🐈' }, desc: '吞噬一切的天灾。', flavor: '脾气和名字一样爆。', formation: ['red-01', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-08', name: '恶尊', rarity: 'red', art: { type: 'emoji', emoji: '🦝' }, desc: '令人闻风丧胆的存在。', flavor: '它跺跺脚，世界抖三抖。', formation: ['red-02', 'thunder-dragon', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-09', name: '血圣', rarity: 'red', art: { type: 'emoji', emoji: '🦖' }, desc: '令人闻风丧胆的存在。', flavor: '脾气和名字一样爆。', formation: ['red-06', 'rainbow-dragon', 'gold-golem', 'thunder-dragon'] },
  { id: 'red-10', name: '湮大公', rarity: 'red', art: { type: 'emoji', emoji: '🪝' }, desc: '令人闻风丧胆的存在。', flavor: '据说它笑过两次。', formation: ['red-04', 'red-03', 'rainbow-dragon', 'thunder-dragon', 'gold-golem'] },
  { id: 'red-11', name: '恨神', rarity: 'red', art: { type: 'emoji', emoji: '🦤' }, desc: '令人闻风丧胆的存在。', flavor: '据说它笑过两次。', formation: ['red-03', 'chaos-lord', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-12', name: '灾收割者', rarity: 'red', art: { type: 'emoji', emoji: '🐵' }, desc: '连天空都被它染红。', flavor: '它跺跺脚，世界抖三抖。', formation: ['red-03', 'thunder-dragon', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-13', name: '灭魔王', rarity: 'red', art: { type: 'emoji', emoji: '🐝' }, desc: '吞噬一切的天灾。', flavor: '据说它笑过两次。', formation: ['red-09', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-14', name: '怨神', rarity: 'red', art: { type: 'emoji', emoji: '🧛' }, desc: '吞噬一切的天灾。', flavor: '脾气和名字一样爆。', formation: ['red-01', 'rainbow-dragon', 'thunder-dragon', 'gold-golem'] },
  { id: 'red-15', name: '恶帝', rarity: 'red', art: { type: 'emoji', emoji: '🐹' }, desc: '令人闻风丧胆的存在。', flavor: '脾气和名字一样爆。', formation: ['chaos-lord', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-16', name: '邪主宰', rarity: 'red', art: { type: 'emoji', emoji: '🌸' }, desc: '令人闻风丧胆的存在。', flavor: '它跺跺脚，世界抖三抖。', formation: ['red-15', 'red-09', 'thunder-dragon', 'gold-golem', 'rainbow-dragon'] },
  { id: 'red-17', name: '灾君', rarity: 'red', art: { type: 'emoji', emoji: '👁️' }, desc: '以毁灭为乐。', flavor: '脾气和名字一样爆。', formation: ['red-02', 'gold-golem', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-18', name: '厄狱长', rarity: 'red', art: { type: 'emoji', emoji: '⛄' }, desc: '令人闻风丧胆的存在。', flavor: '据说它笑过两次。', formation: ['red-14', 'red-03', 'gold-golem', 'rainbow-dragon'] },
  { id: 'black-01', name: '恒归墟', rarity: 'black', art: { type: 'emoji', emoji: '🦆' }, desc: '与永恒同寿。', flavor: '它打个盹就是一万年。', formation: ['void-dragon', 'abyss-lord', 'chaos-lord', 'storm-lord'] },
  { id: 'black-02', name: '万天尊', rarity: 'black', art: { type: 'emoji', emoji: '🦴' }, desc: '祂的过往无人知晓。', flavor: '它打个盹就是一万年。', formation: ['black-01', 'abyss-lord', 'void-dragon', 'chaos-lord'] },
  { id: 'black-03', name: '太造物', rarity: 'black', art: { type: 'emoji', emoji: '🐗' }, desc: '凝视它的人终将迷失。', flavor: '它打个盹就是一万年。', formation: ['abyss-lord', 'void-dragon', 'black-01', 'chaos-lord', 'storm-lord'] },
  { id: 'black-04', name: '古天尊', rarity: 'black', art: { type: 'emoji', emoji: '🐢' }, desc: '凝视它的人终将迷失。', flavor: '没人敢追问它的过去。', formation: ['black-02', 'void-dragon', 'chaos-lord'] },
  { id: 'black-05', name: '虚道祖', rarity: 'black', art: { type: 'emoji', emoji: '🪸' }, desc: '凝视它的人终将迷失。', flavor: '没人敢追问它的过去。', formation: ['black-03', 'void-dragon', 'black-01', 'storm-lord'] },
  { id: 'black-06', name: '古终焉', rarity: 'black', art: { type: 'emoji', emoji: '🐨' }, desc: '凝视它的人终将迷失。', flavor: '没人敢追问它的过去。', formation: ['black-04', 'black-03', 'abyss-lord', 'void-dragon', 'chaos-lord'] },
  { id: 'black-07', name: '万寂灭', rarity: 'black', art: { type: 'emoji', emoji: '⚔️' }, desc: '祂的过往无人知晓。', flavor: '没人敢追问它的过去。', formation: ['black-02', 'black-05', 'chaos-lord'] },
  { id: 'black-08', name: '万古神', rarity: 'black', art: { type: 'emoji', emoji: '🌺' }, desc: '超脱凡世的存在。', flavor: '没人敢追问它的过去。', formation: ['black-02', 'abyss-lord', 'black-03', 'black-06', 'chaos-lord', 'storm-lord'] },
  { id: 'black-09', name: '终道祖', rarity: 'black', art: { type: 'emoji', emoji: '🦦' }, desc: '祂的过往无人知晓。', flavor: '它打个盹就是一万年。', formation: ['black-02', 'black-04', 'chaos-lord'] },
  { id: 'black-10', name: '永太初', rarity: 'black', art: { type: 'emoji', emoji: '🦗' }, desc: '祂的过往无人知晓。', flavor: '没人敢追问它的过去。', formation: ['black-02', 'black-03', 'storm-lord'] },
  { id: 'black-11', name: '始轮回', rarity: 'black', art: { type: 'emoji', emoji: '📿' }, desc: '与永恒同寿。', flavor: '它打个盹就是一万年。', formation: ['black-02', 'abyss-lord', 'black-03', 'black-04', 'storm-lord'] },
  { id: 'black-12', name: '归归墟', rarity: 'black', art: { type: 'emoji', emoji: '❄️' }, desc: '与永恒同寿。', flavor: '没人敢追问它的过去。', formation: ['black-04', 'black-01', 'chaos-lord', 'storm-lord'] },
  { id: 'black-13', name: '太墓主', rarity: 'black', art: { type: 'emoji', emoji: '🦑' }, desc: '与永恒同寿。', flavor: '它打个盹就是一万年。', formation: ['black-12', 'black-07', 'chaos-lord', 'storm-lord'] },
  { id: 'black-14', name: '亘虚无', rarity: 'black', art: { type: 'emoji', emoji: '🗝️' }, desc: '祂的过往无人知晓。', flavor: '它打个盹就是一万年。', formation: ['black-09', 'black-12', 'storm-lord', 'chaos-lord'] },
  { id: 'black-15', name: '虚寂灭', rarity: 'black', art: { type: 'emoji', emoji: '🐂' }, desc: '超脱凡世的存在。', flavor: '没人敢追问它的过去。', formation: ['black-04', 'black-11', 'black-03', 'storm-lord'] },
  { id: 'black-16', name: '亘天尊', rarity: 'black', art: { type: 'emoji', emoji: '🐰' }, desc: '祂的过往无人知晓。', flavor: '它已经忘了自己有多强。', formation: ['black-09', 'black-05', 'black-12', 'black-13', 'chaos-lord'] },
  { id: 'black-17', name: '无造物', rarity: 'black', art: { type: 'emoji', emoji: '🦫' }, desc: '与永恒同寿。', flavor: '没人敢追问它的过去。', formation: ['black-02', 'black-14', 'black-05', 'storm-lord'] },
  { id: 'black-18', name: '玄太初', rarity: 'black', art: { type: 'emoji', emoji: '⚖️' }, desc: '祂的过往无人知晓。', flavor: '它已经忘了自己有多强。', formation: ['black-09', 'black-02', 'black-10', 'storm-lord', 'chaos-lord'] },
];

CARDS.forEach((c, i) => { c.no = i + 1; });

const CARD_MAP = {};
CARDS.forEach(c => { CARD_MAP[c.id] = c; });

const CONFIG = {
  VERSION: '1.0.0',
  INTERVAL_BASE: 10,
  INTERVAL_EXP: 0.4956,
  MIN_INTERVAL: 0.005,
  OFFLINE_CAP_HOURS: 8,
  FRAG_COST_PER_DRAW: 10,
};
