const RARITIES = {
  white:   { name: '白卡',   order: 0, color: '#9ca3af', weight: 55,      basePower: 1,       frag: 1 },
green:   { name: '绿卡',   order: 1, color: '#16a34a', weight: 7.3,     basePower: 10,      frag: 2 },
  blue:    { name: '蓝卡',   order: 2, color: '#2563eb', weight: 2.5,     basePower: 20,      frag: 17 },
  purple:  { name: '紫卡',   order: 3, color: '#7c3aed', weight: 0.5,     basePower: 45,      frag: 85 },
  gold:    { name: '金卡',   order: 4, color: '#d97706', weight: 0.1,     basePower: 107,     frag: 425 },
  red:     { name: '红卡',   order: 5, color: '#dc2626', weight: 0.004,    basePower: 12000,   frag: 10628 },
  black:   { name: '黑卡',   order: 6, color: '#111827', weight: 0.0001,  basePower: 80000,   frag: 425127 },
  rainbow: { name: '炫彩卡', order: 7, color: 'rainbow', weight: 0.00002, basePower: 2000000, frag: 2125634 },
};

const RARITY_LIST = Object.keys(RARITIES).map(k => ({ id: k, ...RARITIES[k] })).sort((a, b) => a.order - b.order);

const CARDS = [
  { id: 'egg-rainbow',  name: '炫彩蛋',     rarity: 'white',  start: true, unique: true, art: { type: 'egg', colors: 'rainbow' },               desc: '传说中集齐五种元素之蛋才会孵化的神奇蛋。',                flavor: '它只是一颗白卡蛋，但梦想是炫彩的。',             formation: ['egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'egg-gold',     name: '金蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ffe9a8', '#f5b52e'] },  desc: '沉甸甸的蛋，隐约透出金光。',                              flavor: '晃一晃，里面有叮当声。',                        formation: [] },
  { id: 'egg-wood',     name: '木蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#e0d3b0', '#8a6b3f'] },  desc: '外壳带着树皮纹路的蛋。',                                  flavor: '插进土里好像会发芽。',                          formation: [] },
  { id: 'egg-water',    name: '水蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#d6ecff', '#4da3ff'] },  desc: '轻轻晃动，能听到水声的蛋。',                              flavor: '永远潮乎乎的。',                                formation: [] },
  { id: 'egg-fire',     name: '火蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ffe0cc', '#ff7a45'] },  desc: '摸上去热乎乎的蛋。',                                      flavor: '冬天抱着它睡觉。',                              formation: [] },
  { id: 'egg-earth',    name: '土蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ecd9b8', '#96704a'] },  desc: '沾着泥土气息的蛋。',                                      flavor: '重得像个哑铃。',                                formation: [] },
  { id: 'sapling',      name: '小树苗',     rarity: 'green',  art: { type: 'emoji', emoji: '🌱' },  desc: '需要三颗蛋的陪伴才能茁壮成长。',            flavor: '一天长一片叶子。',                              formation: ['egg-wood', 'egg-earth', 'egg-water'] },
  { id: 'ember',        name: '小火苗',     rarity: 'green',  art: { type: 'emoji', emoji: '🔥' },  desc: '一点就着的小脾气。',                        flavor: '吹口气就会灭。',                              formation: ['egg-fire', 'egg-wood', 'egg-gold'] },
  { id: 'droplet',      name: '小水灵',     rarity: 'green',  art: { type: 'emoji', emoji: '💧' },  desc: '整天咕嘟咕嘟冒泡。',                        flavor: '哭的时候会下雨。',                            formation: ['egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'forest-guard', name: '森林守卫',   rarity: 'blue',   art: { type: 'emoji', emoji: '🌳' },  desc: '森林里最可靠的伙伴。',                      flavor: '每一片叶子都在放哨。',                        formation: ['sapling', 'egg-wood', 'egg-earth'] },
  { id: 'lava-turtle',  name: '岩浆龟',     rarity: 'blue',   art: { type: 'emoji', emoji: '🐢' },  desc: '龟壳里住着一座小火山。',                    flavor: '走得慢，但挡不住。',                          formation: ['ember', 'egg-fire'] },
  { id: 'elementalist', name: '元素使',     rarity: 'purple', art: { type: 'emoji', emoji: '⚗️' },  desc: '调和水火木土的大师。',                      flavor: '配方是机密。',                                formation: ['egg-fire', 'egg-water', 'egg-wood', 'egg-earth'] },
  { id: 'rainbow-dragon', name: '彩虹龙',   rarity: 'gold',   art: { type: 'emoji', emoji: '🐉' },  desc: '横跨天际的传说之龙。',                      flavor: '它飞过的地方会下糖果雨。',                  formation: ['elementalist', 'forest-guard', 'lava-turtle', 'ember', 'droplet', 'sapling'] },
  { id: 'chaos-lord',   name: '混沌魔王',   rarity: 'red',    art: { type: 'emoji', emoji: '👹' },  desc: '吞噬光明与秩序。',                          flavor: '连影子都害怕它。',                            formation: ['rainbow-dragon', 'elementalist', 'egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'abyss-lord',   name: '深渊之主',   rarity: 'black',  art: { type: 'emoji', emoji: '🕳️' },  desc: '凝视深渊者，终将被深渊凝视。',              flavor: '没人见过它的真面目。',                        formation: ['chaos-lord', 'rainbow-dragon', 'elementalist', 'egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'creator',      name: '创世神',     rarity: 'rainbow', art: { type: 'emoji', emoji: '✨' },  desc: '一切卡片的起源。',                          flavor: '它给自己写的登场台词。',                      formation: ['abyss-lord', 'chaos-lord', 'rainbow-dragon', 'elementalist'] },
  { id: 'egg-stone',    name: '石头蛋',     rarity: 'white',  art: { type: 'egg', colors: ['#e2e8f0', '#94a3b8'] },  desc: '重得像块石头的蛋。',                      flavor: '砸核桃挺好用。',                          formation: [] },
  { id: 'egg-thunder',  name: '雷蛋',       rarity: 'white',  art: { type: 'egg', colors: ['#fef9c3', '#eab308'] },  desc: '偶尔会噼啪作响的蛋。',                    flavor: '摸之前记得先洗手。',                      formation: [] },
  { id: 'egg-ice',      name: '冰蛋',       rarity: 'white',  art: { type: 'egg', colors: ['#e0f2fe', '#38bdf8'] },  desc: '摸起来凉飕飕的蛋。',                      flavor: '夏天想抱着它。',                          formation: [] },
  { id: 'rockling',     name: '小石头',     rarity: 'green',  art: { type: 'emoji', emoji: '🪨' },  desc: '一块会滚的小石头。',                      flavor: '滚起来比看起来快。',                      formation: ['egg-stone', 'egg-gold', 'egg-wood'] },
  { id: 'cloudling',    name: '小云朵',     rarity: 'green',  art: { type: 'emoji', emoji: '☁️' },  desc: '软绵绵的云朵精灵。',                      flavor: '心情好就下雨。',                          formation: ['egg-water', 'egg-thunder', 'egg-ice'] },
  { id: 'blossom',      name: '小花精',     rarity: 'green',  art: { type: 'emoji', emoji: '🌸' },  desc: '从花苞里钻出来的小家伙。',                flavor: '走到哪香到哪。',                          formation: ['egg-wood', 'egg-water', 'egg-earth'] },
  { id: 'thunder-spirit', name: '雷灵',     rarity: 'blue',   art: { type: 'emoji', emoji: '⚡' },  desc: '脾气火爆的电系精灵。',                    flavor: '打雷天最精神。',                          formation: ['cloudling', 'egg-thunder', 'egg-water'] },
  { id: 'ice-wisp',     name: '冰灵',       rarity: 'blue',   art: { type: 'emoji', emoji: '❄️' },  desc: '指尖掠过霜雪的精灵。',                    flavor: '夏天站在它身边很凉快。',                  formation: ['blossom', 'egg-ice', 'egg-wood'] },
  { id: 'rock-golem',   name: '岩甲兵',     rarity: 'blue',   art: { type: 'emoji', emoji: '🗿' },  desc: '岩石堆成的沉默士兵。',                    flavor: '它的笑点很低。',                          formation: ['rockling', 'egg-earth', 'egg-gold'] },
  { id: 'storm-witch',  name: '风暴女巫',   rarity: 'purple', art: { type: 'emoji', emoji: '🧙' },  desc: '把闪电装进帽子的女巫。',                  flavor: '帽子其实是晴雨计。',                      formation: ['thunder-spirit', 'cloudling', 'egg-thunder', 'egg-ice'] },
  { id: 'crystal-golem', name: '水晶魔像',  rarity: 'purple', art: { type: 'emoji', emoji: '💎' },  desc: '浑身剔透的水晶造物。',                    flavor: '在阳光下会闪瞎眼。',                      formation: ['rock-golem', 'ice-wisp', 'egg-ice', 'egg-gold'] },
  { id: 'thunder-dragon', name: '雷光龙',   rarity: 'gold',   art: { type: 'emoji', emoji: '🐲' },  desc: '御雷而行的东方之龙。',                    flavor: '尾巴一甩就是一道闪电。',                  formation: ['storm-witch', 'thunder-spirit', 'cloudling', 'ice-wisp', 'egg-thunder', 'egg-ice'] },
  { id: 'gold-golem',   name: '金晶王',     rarity: 'gold',   art: { type: 'emoji', emoji: '👑' },  desc: '统治矿物王国的黄金之王。',                flavor: '它的王座是块大金矿。',                    formation: ['crystal-golem', 'rock-golem', 'rockling', 'egg-gold', 'egg-wood', 'egg-earth'] },
  { id: 'storm-lord',   name: '风暴之主',   rarity: 'red',    art: { type: 'emoji', emoji: '🌩️' },  desc: '将整片天空握在手中。',                    flavor: '它一打喷嚏就会刮台风。',                  formation: ['thunder-dragon', 'storm-witch', 'gold-golem', 'egg-thunder', 'egg-gold'] },
  { id: 'void-dragon',  name: '虚空之龙',   rarity: 'black',  art: { type: 'emoji', emoji: '🌀' },  desc: '蛰伏于虚空尽头的古龙。',                  flavor: '它的叹息就是黑洞。',                      formation: ['storm-lord', 'thunder-dragon', 'gold-golem', 'crystal-golem', 'egg-thunder', 'egg-ice'] },
  { id: 'green-01', name: '碧使', rarity: 'green', art: { type: 'emoji', emoji: '🕯️' }, desc: '举着烛火巡夜的信使，天亮前绝不眨眼。', flavor: '烛芯是它珍藏的一根草茎。', formation: ['sapling', 'ember', 'blossom'] },
  { id: 'green-02', name: '蒲学徒', rarity: 'green', art: { type: 'emoji', emoji: '🌌' }, desc: '趴在草尖上数星星的学徒，数到 99 就会睡着。', flavor: '星星的数目每晚都变，它记了三年账。', formation: ['cloudling', 'blossom'] },
  { id: 'green-03', name: '柳使', rarity: 'green', art: { type: 'emoji', emoji: '🍃' }, desc: '顶着伞盖躲雨的柳使，雨停也不肯收伞。', flavor: '伞下藏着三颗松果，是它的存粮。', formation: ['rockling', 'green-01', 'ember'] },
  { id: 'green-04', name: '蔓仆', rarity: 'green', art: { type: 'emoji', emoji: '🍀' }, desc: '用藤蔓编花环的蔓仆，手比名字巧十倍。', flavor: '编坏的花环它都留着，说是历史。', formation: ['green-03', 'blossom'] },
  { id: 'green-05', name: '果精灵', rarity: 'green', art: { type: 'emoji', emoji: '🍎' }, desc: '守着果林第一枚果实的精灵，谁先咬谁挨嚎。', flavor: '嚎声是吓鸟的，不是真凶。', formation: ['blossom', 'rockling'] },
  { id: 'green-06', name: '芽仆', rarity: 'green', art: { type: 'emoji', emoji: '🫘' }, desc: '把每颗种子当孩子盯的芽仆，风雨无阻。', flavor: '它吼声很响，其实怕蜜蜂。', formation: ['rockling', 'green-02', 'blossom'] },
  { id: 'green-07', name: '芽芽', rarity: 'green', art: { type: 'emoji', emoji: '🪴' }, desc: '破土时只有拇指大，现在还是拇指大。', flavor: '它坚信自己迟早长成大树。', formation: ['sapling', 'cloudling', 'green-04'] },
  { id: 'green-08', name: '苔童', rarity: 'green', art: { type: 'emoji', emoji: '🍄' }, desc: '在石缝间穿行的小苔童，走路悄无声息。', flavor: '脚底的绿毯是它自己种的。', formation: ['green-01', 'green-05', 'sapling'] },
  { id: 'green-09', name: '蔓芽', rarity: 'green', art: { type: 'emoji', emoji: '🌵' }, desc: '从火山灰里钻出的芽，叶尖烫手。', flavor: '冒烟是在生闷气，浇水就好。', formation: ['sapling', 'green-03'] },
  { id: 'green-10', name: '竹祭司', rarity: 'green', art: { type: 'emoji', emoji: '🎋' }, desc: '用竹节占卜天气的祭司，十占九不准。', flavor: '不准的时候它说是风向的错。', formation: ['blossom', 'droplet', 'green-05'] },
  { id: 'green-11', name: '松族', rarity: 'green', art: { type: 'emoji', emoji: '🌰' }, desc: '把松果当钱币攒的松族，只进不出。', flavor: '小金库在树洞里，钥匙是根羽毛。', formation: ['green-02', 'blossom', 'droplet'] },
  { id: 'green-12', name: '青卫', rarity: 'green', art: { type: 'emoji', emoji: '🦊' }, desc: '在林间巡逻的青卫，尾巴竖着当旗。', flavor: '它记仇记恩都刻在石头上。', formation: ['green-11', 'green-06'] },
  { id: 'green-13', name: '苍卫', rarity: 'green', art: { type: 'emoji', emoji: '🦉' }, desc: '蹲在溪边看虫子的苍卫，一看一整天。', flavor: '每条虫它都给取了名字。', formation: ['green-06', 'ember', 'cloudling'] },
  { id: 'green-14', name: '竹姬', rarity: 'green', art: { type: 'emoji', emoji: '🎍' }, desc: '竹节里住着的公主，敲三下竹竿她开花。', flavor: '她一笑，整片竹林跟着晃。', formation: ['green-02', 'green-04', 'cloudling'] },
  { id: 'green-15', name: '苔姬', rarity: 'green', art: { type: 'emoji', emoji: '🌿' }, desc: '披着绿斗篷的苔姬，走到哪绿到哪。', flavor: '她的裙摆是活的草坪。', formation: ['ember', 'green-12', 'cloudling'] },
  { id: 'green-16', name: '蒲祭司', rarity: 'green', art: { type: 'emoji', emoji: '🌼' }, desc: '举蒲公英给迷路者指路的祭司。', flavor: '指错方向时，它说这是命运。', formation: ['green-04', 'green-05', 'green-12'] },
  { id: 'blue-01', name: '泉灵', rarity: 'blue', art: { type: 'emoji', emoji: '🧿' }, desc: '泉眼深处睁着眼睛的灵，眨一下泉水就冒泡。', flavor: '它数得清每滴水回湖的路。', formation: ['thunder-spirit', 'lava-turtle', 'sapling'] },
  { id: 'blue-02', name: '雾士', rarity: 'blue', art: { type: 'emoji', emoji: '🌫️' }, desc: '晨雾里站岗的士，太阳出来就下班。', flavor: '它的制服是露水做的，晒晒就干。', formation: ['lava-turtle', 'sapling'] },
  { id: 'blue-03', name: '雪灵', rarity: 'blue', art: { type: 'emoji', emoji: '🌨️' }, desc: '雪堆里打滚的灵体，指尖一碰就化。', flavor: '它怕热，但更怕没人陪它堆雪人。', formation: ['blue-01', 'rockling'] },
  { id: 'blue-04', name: '澜使', rarity: 'blue', art: { type: 'emoji', emoji: '🌊' }, desc: '踏浪尖送信的使者，信封从不上潮。', flavor: '它的信封是贝壳，邮戳是水花。', formation: ['blue-03', 'blossom'] },
  { id: 'blue-05', name: '澜龙', rarity: 'blue', art: { type: 'emoji', emoji: '🐊' }, desc: '把湖面当镜子照的澜龙，发型不能乱。', flavor: '它教青蛙游泳，青蛙学会了潜泳。', formation: ['thunder-spirit', 'blue-04', 'rockling', 'blossom'] },
  { id: 'blue-06', name: '湖蟹', rarity: 'blue', art: { type: 'emoji', emoji: '🦀' }, desc: '横着走的湖蟹，钳子里夹着湖底机密。', flavor: '机密只有一条：湖底全是泥。', formation: ['blue-04', 'blue-01', 'droplet'] },
  { id: 'blue-07', name: '波精', rarity: 'blue', art: { type: 'emoji', emoji: '💦' }, desc: '收集涟漪当收藏品的波精，一格一枚。', flavor: '最贵的一枚，是蜻蜓点水的。', formation: ['blue-04', 'ice-wisp', 'sapling'] },
  { id: 'blue-08', name: '雪卫', rarity: 'blue', art: { type: 'emoji', emoji: '🐼' }, desc: '守在冰缘的雪卫，从不让自己打滑。', flavor: '它让每片雪都落得整整齐齐。', formation: ['blue-07', 'ember', 'droplet'] },
  { id: 'blue-09', name: '冰兽', rarity: 'blue', art: { type: 'emoji', emoji: '🦣' }, desc: '背着冰壳的兽，呼吸喷白雾。', flavor: '它打喷嚏能冻半条河，所以忍着。', formation: ['blue-06', 'ember'] },
  { id: 'blue-10', name: '瀑使', rarity: 'blue', art: { type: 'emoji', emoji: '⛲' }, desc: '把瀑布拧成绳子的瀑使，力大无穷。', flavor: '拧出的水绳，能晾一山的衣裳。', formation: ['blue-01', 'blue-03', 'cloudling', 'droplet'] },
  { id: 'blue-11', name: '波师', rarity: 'blue', art: { type: 'emoji', emoji: '📖' }, desc: '研究水波的老师，讲课从来不用稿。', flavor: '它说水波是唯一听讲的学生。', formation: ['forest-guard', 'rock-golem', 'sapling'] },
  { id: 'blue-12', name: '湖鲸', rarity: 'blue', art: { type: 'emoji', emoji: '🐋' }, desc: '沉在湖底的鲸，背上盖着一座小城。', flavor: '它浮上来，是为了换一座城。', formation: ['blue-03', 'blue-05', 'ember'] },
  { id: 'blue-13', name: '澜兽', rarity: 'blue', art: { type: 'emoji', emoji: '🦌' }, desc: '四蹄踏水不沉的澜兽，跑起来像一堵浪。', flavor: '它踩出的涟漪十年不散。', formation: ['lava-turtle', 'rockling', 'sapling'] },
  { id: 'blue-14', name: '渊龙', rarity: 'blue', art: { type: 'emoji', emoji: '🐍' }, desc: '盘在深水的渊龙，鳞片剪开月光。', flavor: '它不上浮，除非有人讲笑话。', formation: ['blue-10', 'blue-05', 'rockling', 'sapling'] },
  { id: 'blue-15', name: '湖士', rarity: 'blue', art: { type: 'emoji', emoji: '🐡' }, desc: '一被夸奖就膨胀的湖士，胀成球弹走。', flavor: '它弹走的方向，总是朝着夸奖声。', formation: ['blue-13', 'blue-08', 'ember', 'droplet'] },
  { id: 'blue-16', name: '瀑鲛', rarity: 'blue', art: { type: 'emoji', emoji: '⚒️' }, desc: '在瀑布里打铁的鲛人，锤声如雷。', flavor: '它打的铁器，连河水都喜欢。', formation: ['lava-turtle', 'ember', 'rockling'] },
  { id: 'purple-01', name: '魅将', rarity: 'purple', art: { type: 'emoji', emoji: '🧜' }, desc: '魅惑之术师从海巫，歌声能定潮汐。', flavor: '它的咒语押韵，失败也押韵。', formation: ['storm-witch', 'elementalist', 'lava-turtle'] },
  { id: 'purple-02', name: '辰伯爵', rarity: 'purple', art: { type: 'emoji', emoji: '🎩' }, desc: '领口永远立着的伯爵，怕冷也怕打雷。', flavor: '雷雨天它躲在最厚的书后面。', formation: ['storm-witch', 'purple-01', 'forest-guard', 'ice-wisp'] },
  { id: 'purple-03', name: '星术士', rarity: 'purple', art: { type: 'emoji', emoji: '🔭' }, desc: '挎着星图篮子的术士，摘星当晚餐。', flavor: '篮子里的星星到早晨就化了。', formation: ['purple-01', 'forest-guard'] },
  { id: 'purple-04', name: '魅伯爵', rarity: 'purple', art: { type: 'emoji', emoji: '🦾' }, desc: '铁臂伯爵，握手时从不使力。', flavor: '它那双手其实是借来的。', formation: ['crystal-golem', 'purple-03', 'rock-golem', 'thunder-spirit'] },
  { id: 'purple-05', name: '影术士', rarity: 'purple', art: { type: 'emoji', emoji: '🗡️' }, desc: '把影子削成匕首的术士，出鞘无声。', flavor: '它从不背对光。', formation: ['purple-02', 'purple-03', 'lava-turtle'] },
  { id: 'purple-06', name: '夜爵', rarity: 'purple', art: { type: 'emoji', emoji: '🦎' }, desc: '贴着墙根行走的夜爵，像一片会喘气的影子。', flavor: '它断掉的尾巴，第二天长回来。', formation: ['crystal-golem', 'purple-02', 'forest-guard'] },
  { id: 'purple-07', name: '梦巫师', rarity: 'purple', art: { type: 'emoji', emoji: '🐑' }, desc: '数羊入眠的巫师，数到第一千只会被羊叫醒。', flavor: '它卖的梦，签收要按手印。', formation: ['purple-02', 'ice-wisp'] },
  { id: 'purple-08', name: '冥侯', rarity: 'purple', art: { type: 'emoji', emoji: '🪓' }, desc: '挥斧劈开夜色的冥侯，斧刃从来不锈。', flavor: '它说斧头比月亮勤快。', formation: ['purple-04', 'ice-wisp'] },
  { id: 'purple-09', name: '月巫师', rarity: 'purple', art: { type: 'emoji', emoji: '🐸' }, desc: '月光下施法的巫师，蟾蜍是它的坐骑。', flavor: '它念咒，坐骑打嗝，咒语就破了。', formation: ['purple-04', 'ice-wisp', 'rock-golem'] },
  { id: 'purple-10', name: '月爵', rarity: 'purple', art: { type: 'emoji', emoji: '🧝' }, desc: '精灵血统的月爵，耳朵尖得像月牙。', flavor: '它听得到花瓣落地的声音。', formation: ['storm-witch', 'lava-turtle'] },
  { id: 'purple-11', name: '夜将', rarity: 'purple', art: { type: 'emoji', emoji: '🌙' }, desc: '夜巡的将军，披风是藤蔓织的。', flavor: '它走过的地方，第二天冒新芽。', formation: ['purple-07', 'ice-wisp', 'rock-golem'] },
  { id: 'purple-12', name: '夜司祭', rarity: 'purple', art: { type: 'emoji', emoji: '🐳' }, desc: '深海唱诗班的司祭，嗓音低沉如鲸。', flavor: '它的祷词能让海面平静。', formation: ['purple-05', 'purple-09', 'lava-turtle'] },
  { id: 'purple-13', name: '辰爵', rarity: 'purple', art: { type: 'emoji', emoji: '🌅' }, desc: '黎明前上岗的辰爵，抱着钟楼打盹。', flavor: '它误点的钟声，大家都不怪它。', formation: ['purple-03', 'forest-guard'] },
  { id: 'purple-14', name: '暮侯', rarity: 'purple', art: { type: 'emoji', emoji: '🪶' }, desc: '黄昏收集羽毛的侯爵，帽子上插满鸟羽。', flavor: '每根羽毛它都记得是谁掉的。', formation: ['purple-02', 'purple-05', 'ice-wisp'] },
  { id: 'purple-15', name: '暮骑', rarity: 'purple', art: { type: 'emoji', emoji: '🦢' }, desc: '骑着天鹅巡逻的暮骑，披风是晚霞。', flavor: '它从不参加晨会。', formation: ['purple-14', 'thunder-spirit'] },
  { id: 'purple-16', name: '夜祭司', rarity: 'purple', art: { type: 'emoji', emoji: '⭐' }, desc: '给迷途者指星的祭司，指哪颗哪颗亮。', flavor: '它从不迷路，它说星星认得它。', formation: ['storm-witch', 'purple-06', 'rock-golem', 'thunder-spirit'] },
  { id: 'gold-01', name: '冠爵', rarity: 'gold', art: { type: 'emoji', emoji: '⛏️' }, desc: '矿脉中诞生的爵爷，王冠是铁镐改的。', flavor: '它说权力会生锈，所以常磨。', formation: ['thunder-dragon', 'crystal-golem'] },
  { id: 'gold-02', name: '虎王', rarity: 'gold', art: { type: 'emoji', emoji: '🐯' }, desc: '虎纹陶罐里醒来的王，一吼山门开。', flavor: '它吃早餐时要铺餐巾。', formation: ['thunder-dragon', 'elementalist', 'crystal-golem'] },
  { id: 'gold-03', name: '鸾宰相', rarity: 'gold', art: { type: 'emoji', emoji: '🧪' }, desc: '炼金术出身的宰相，奏折是配方。', flavor: '它的计谋都带一点点药味。', formation: ['gold-golem', 'storm-witch', 'elementalist'] },
  { id: 'gold-04', name: '君元帅', rarity: 'gold', art: { type: 'emoji', emoji: '⚜️' }, desc: '盾徽镶金的元帅，凯旋也要按军礼。', flavor: '它给每位士兵都留了位置。', formation: ['gold-02', 'rainbow-dragon', 'storm-witch'] },
  { id: 'gold-05', name: '豹爵', rarity: 'gold', art: { type: 'emoji', emoji: '🐆' }, desc: '踩着晚霞巡山的豹爵，步子像鼓点。', flavor: '它的领地日落时最好看。', formation: ['gold-golem', 'elementalist', 'storm-witch'] },
  { id: 'gold-06', name: '鹤将军', rarity: 'gold', art: { type: 'emoji', emoji: '🦩' }, desc: '白头鹤将军，塔楼顶就是它的瞭望台。', flavor: '它低头是为了看清谁在敬礼。', formation: ['gold-05', 'gold-golem', 'storm-witch'] },
  { id: 'gold-07', name: '贤元帅', rarity: 'gold', art: { type: 'emoji', emoji: '🗿' }, desc: '石像里走出的元帅，军令刻在额上。', flavor: '它站岗时，连风都要绕路。', formation: ['gold-01', 'gold-02', 'elementalist', 'crystal-golem'] },
  { id: 'gold-08', name: '鹤王', rarity: 'gold', art: { type: 'emoji', emoji: '🦅' }, desc: '朱顶鹤王，翎羽沾着夕阳的血色。', flavor: '它一展翅，半边天都红了。', formation: ['gold-05', 'rainbow-dragon', 'crystal-golem', 'storm-witch'] },
  { id: 'gold-09', name: '鸾元帅', rarity: 'gold', art: { type: 'emoji', emoji: '🦚' }, desc: '披星执剑的鸾元帅，剑鞘缀着彗尾。', flavor: '它拔剑的速度比流星快。', formation: ['gold-04', 'gold-07', 'storm-witch'] },
  { id: 'gold-10', name: '麟预言家', rarity: 'gold', art: { type: 'emoji', emoji: '🦄' }, desc: '踏浪而行的麟预言家，浪尖写满签文。', flavor: '它预言过海啸，也预言过晴日。', formation: ['gold-05', 'elementalist'] },
  { id: 'gold-11', name: '豹君主', rarity: 'gold', art: { type: 'emoji', emoji: '🦐' }, desc: '虾钳王座的君主，钳子镀了金。', flavor: '它敲三下王座，潮水就退。', formation: ['thunder-dragon', 'elementalist'] },
  { id: 'gold-12', name: '麟宰相', rarity: 'gold', art: { type: 'emoji', emoji: '🐎' }, desc: '袖中藏花的宰相，谈判桌上花比话多。', flavor: '它送出去的花都另有深意。', formation: ['thunder-dragon', 'gold-01', 'elementalist', 'storm-witch'] },
  { id: 'gold-13', name: '冠预言家', rarity: 'gold', art: { type: 'emoji', emoji: '🪐' }, desc: '星环缠身的预言家，句句带光环。', flavor: '它预言自己明天也会预言。', formation: ['rainbow-dragon', 'gold-golem', 'elementalist', 'storm-witch'] },
  { id: 'gold-14', name: '傲祭司', rarity: 'gold', art: { type: 'emoji', emoji: '🐄' }, desc: '牛角祭坛的祭司，布道声如闷雷。', flavor: '它的信徒是整片牧场。', formation: ['gold-10', 'gold-13', 'crystal-golem'] },
  { id: 'gold-15', name: '权宰相', rarity: 'gold', art: { type: 'emoji', emoji: '📜' }, desc: '权杖嵌钻的宰相，说话自带回音。', flavor: '它点头，国库就响一声。', formation: ['thunder-dragon', 'storm-witch', 'elementalist'] },
  { id: 'gold-16', name: '皇骑士长', rarity: 'gold', art: { type: 'emoji', emoji: '🔮' }, desc: '水晶球当盾的骑士长，能看见三秒后。', flavor: '它总说：我早知道了，但谢谢。', formation: ['gold-03', 'crystal-golem', 'storm-witch'] },
  { id: 'red-01', name: '魔尊', rarity: 'red', art: { type: 'emoji', emoji: '🪄' }, desc: '魔杖所指皆成焦土的尊上，从不说第二遍。', flavor: '它唯一的软肋是怕冷。', formation: ['chaos-lord', 'storm-lord', 'gold-golem', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-02', name: '焚魔王', rarity: 'red', art: { type: 'emoji', emoji: '⚱️' }, desc: '骨灰瓮里重生的魔王，点火不用打火石。', flavor: '它睡觉时床铺是温的。', formation: ['chaos-lord', 'storm-lord', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-03', name: '蚀主', rarity: 'red', art: { type: 'emoji', emoji: '🤖' }, desc: '吞吃岩石的机械之主，齿轮就是牙齿。', flavor: '它锈了会下雨，雨就是机油。', formation: ['storm-lord', 'red-02', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-04', name: '灭帝', rarity: 'red', art: { type: 'emoji', emoji: '💥' }, desc: '一脚踏平城邦的灭帝，落地从不回头。', flavor: '它踩过的地方，草长得特别高。', formation: ['red-01', 'storm-lord', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-05', name: '厄暴君', rarity: 'red', art: { type: 'emoji', emoji: '👽' }, desc: '来自星外的暴君，瞳孔是裂缝。', flavor: '它数不清地球的月亮有几个。', formation: ['storm-lord', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-06', name: '邪收割者', rarity: 'red', art: { type: 'emoji', emoji: '🌾' }, desc: '日出时收魂的收割者，镰刀镀着晨光。', flavor: '它其实想改行种麦子。', formation: ['red-05', 'red-03', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-07', name: '血吞噬者', rarity: 'red', art: { type: 'emoji', emoji: '🐈' }, desc: '舔干净血迹的吞噬者，像一只大猫。', flavor: '它打盹时呼噜声像雷。', formation: ['red-01', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-08', name: '恶尊', rarity: 'red', art: { type: 'emoji', emoji: '🦝' }, desc: '偷走月光的恶尊，赃物藏在树洞。', flavor: '每月十五它去月下补赃。', formation: ['red-02', 'thunder-dragon', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-09', name: '血圣', rarity: 'red', art: { type: 'emoji', emoji: '🦖' }, desc: '远古血脉的圣兽，鳞片渗着岩浆。', flavor: '它吼一声，火山跟着咳嗽。', formation: ['red-06', 'rainbow-dragon', 'gold-golem', 'thunder-dragon'] },
  { id: 'red-10', name: '湮大公', rarity: 'red', art: { type: 'emoji', emoji: '🪝' }, desc: '钩走一切的大公，钩子上什么都能挂。', flavor: '它钓过一条彩虹，放生了。', formation: ['red-04', 'red-03', 'rainbow-dragon', 'thunder-dragon', 'gold-golem'] },
  { id: 'red-11', name: '恨神', rarity: 'red', art: { type: 'emoji', emoji: '🦤' }, desc: '灭绝名单上的恨神，爪子握紧不放。', flavor: '它恨一切，除了打盹。', formation: ['red-03', 'chaos-lord', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-12', name: '灾收割者', rarity: 'red', art: { type: 'emoji', emoji: '🎒' }, desc: '背着灾袋的收割者，撒豆成祸。', flavor: '它的布袋漏了，灾就小了。', formation: ['red-03', 'thunder-dragon', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-13', name: '灭魔王', rarity: 'red', art: { type: 'emoji', emoji: '🐝' }, desc: '蜂群组成的魔王，散则蜂聚则王。', flavor: '它的蜂针是言出法随。', formation: ['red-09', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-14', name: '怨神', rarity: 'red', art: { type: 'emoji', emoji: '🧛' }, desc: '吸食怨气的古神，怨气当茶饮。', flavor: '它品得出每杯怨气的产地。', formation: ['red-01', 'rainbow-dragon', 'thunder-dragon', 'gold-golem'] },
  { id: 'red-15', name: '恶帝', rarity: 'red', art: { type: 'emoji', emoji: '🐹' }, desc: '鼠面恶帝，朝堂设在粮仓顶上。', flavor: '它批奏折时啃胡萝卜。', formation: ['chaos-lord', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-16', name: '邪主宰', rarity: 'red', art: { type: 'emoji', emoji: '🥀' }, desc: '花瓣染血的邪主宰，美得让人不敢看。', flavor: '它落泪的地方开出血色花。', formation: ['red-15', 'red-09', 'thunder-dragon', 'gold-golem', 'rainbow-dragon'] },
  { id: 'red-17', name: '灾君', rarity: 'red', art: { type: 'emoji', emoji: '👁️' }, desc: '全知之眼只睁一半的灾君。', flavor: '它闭眼时，坏事都在路上。', formation: ['red-02', 'gold-golem', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-18', name: '厄狱长', rarity: 'red', art: { type: 'emoji', emoji: '⛄' }, desc: '冰狱的狱长，钥匙串在雪人身上。', flavor: '它不放任何人走，包括春天。', formation: ['red-14', 'red-03', 'gold-golem', 'rainbow-dragon'] },
  { id: 'black-01', name: '恒归墟', rarity: 'black', art: { type: 'emoji', emoji: '🦆' }, desc: '从归墟浮起的黑鸭，翅膀遮天。', flavor: '它凫水的地方，星海起皱。', formation: ['void-dragon', 'abyss-lord', 'chaos-lord', 'storm-lord'] },
  { id: 'black-02', name: '万天尊', rarity: 'black', art: { type: 'emoji', emoji: '🦴' }, desc: '骨头拼成的天尊，指节拨动星河。', flavor: '它身上的每一根骨都叫过别的名字。', formation: ['black-01', 'abyss-lord', 'void-dragon', 'chaos-lord'] },
  { id: 'black-03', name: '太造物', rarity: 'black', art: { type: 'emoji', emoji: '🐗' }, desc: '创世野猪，獠牙犁开混沌。', flavor: '它拱出来的土，成了山。', formation: ['abyss-lord', 'void-dragon', 'black-01', 'chaos-lord', 'storm-lord'] },
  { id: 'black-04', name: '古天尊', rarity: 'black', art: { type: 'emoji', emoji: '🦕' }, desc: '背着纪元的古天尊，壳上刻满历法。', flavor: '它每走一步，世间过一纪。', formation: ['black-02', 'void-dragon', 'chaos-lord'] },
  { id: 'black-05', name: '虚道祖', rarity: 'black', art: { type: 'emoji', emoji: '🪸' }, desc: '珊瑚长成的道祖，触须触及虚空。', flavor: '它盘坐的地方，海底长出道场。', formation: ['black-03', 'void-dragon', 'black-01', 'storm-lord'] },
  { id: 'black-06', name: '古终焉', rarity: 'black', art: { type: 'emoji', emoji: '🐨' }, desc: '抱着末日树懒，动作慢到时间愿意等。', flavor: '它的缓慢是宇宙唯一的秩序。', formation: ['black-04', 'black-03', 'abyss-lord', 'void-dragon', 'chaos-lord'] },
  { id: 'black-07', name: '万寂灭', rarity: 'black', art: { type: 'emoji', emoji: '⚔️' }, desc: '剑锋所指皆归寂灭的武者。', flavor: '它出剑时，连回音都先死。', formation: ['black-02', 'black-05', 'chaos-lord'] },
  { id: 'black-08', name: '万古神', rarity: 'black', art: { type: 'emoji', emoji: '🌺' }, desc: '花开花落即万古的神，花瓣是纪元。', flavor: '它一转身，花期刚好一亿年。', formation: ['black-02', 'abyss-lord', 'black-03', 'black-06', 'chaos-lord', 'storm-lord'] },
  { id: 'black-09', name: '终道祖', rarity: 'black', art: { type: 'emoji', emoji: '🦦' }, desc: '在水面打坐的道祖，波纹是道纹。', flavor: '它睁眼，水面上映着三千世界。', formation: ['black-02', 'black-04', 'chaos-lord'] },
  { id: 'black-10', name: '永太初', rarity: 'black', art: { type: 'emoji', emoji: '🦗' }, desc: '第一声蝉鸣化成的太初。', flavor: '它的叫声比宇宙还早一瞬。', formation: ['black-02', 'black-03', 'storm-lord'] },
  { id: 'black-11', name: '始轮回', rarity: 'black', art: { type: 'emoji', emoji: '📿' }, desc: '拨动轮回念珠的始祖，一串 108 界。', flavor: '它拨错一颗，就多出一世。', formation: ['black-02', 'abyss-lord', 'black-03', 'black-04', 'storm-lord'] },
  { id: 'black-12', name: '归归墟', rarity: 'black', art: { type: 'emoji', emoji: '🧊' }, desc: '极寒中走向归墟的冰旅者。', flavor: '它脚印里的冰，万年不化。', formation: ['black-04', 'black-01', 'chaos-lord', 'storm-lord'] },
  { id: 'black-13', name: '太墓主', rarity: 'black', art: { type: 'emoji', emoji: '🦑' }, desc: '章鱼触手把守的墓主，墓门是漩涡。', flavor: '它守的不是尸骨，是没人记得的名字。', formation: ['black-12', 'black-07', 'chaos-lord', 'storm-lord'] },
  { id: 'black-14', name: '亘虚无', rarity: 'black', art: { type: 'emoji', emoji: '🗝️' }, desc: '钥匙悬在虚无里的存在，锁孔在万有。', flavor: '它开过的门，都忘记自己有门。', formation: ['black-09', 'black-12', 'storm-lord', 'chaos-lord'] },
  { id: 'black-15', name: '虚寂灭', rarity: 'black', art: { type: 'emoji', emoji: '🐂' }, desc: '牛角抵住寂灭的虚影，一步一虚。', flavor: '它走过的地方，声音都认输。', formation: ['black-04', 'black-11', 'black-03', 'storm-lord'] },
  { id: 'black-16', name: '亘天尊', rarity: 'black', art: { type: 'emoji', emoji: '🐰' }, desc: '月宫玉兔演化成的天尊，捣药声震星河。', flavor: '它捣的不是药，是时间。', formation: ['black-09', 'black-05', 'black-12', 'black-13', 'chaos-lord'] },
  { id: 'black-17', name: '无造物', rarity: 'black', art: { type: 'emoji', emoji: '🦫' }, desc: '用倒影筑坝的造物，坝拦的是因果。', flavor: '它咬断的木头，落水即成舟。', formation: ['black-02', 'black-14', 'black-05', 'storm-lord'] },
{ id: 'black-18', name: '玄太初', rarity: 'black', art: { type: 'emoji', emoji: '⚖️' }, desc: '称量一切的玄天秤，两头是天平。', flavor: '它称过太阳，八两。', formation: ['black-09', 'black-02', 'black-10', 'storm-lord', 'chaos-lord'] },
  { id: 'qinghuan-miao', name: '晴幻喵', rarity: 'rainbow', art: { type: 'emoji', emoji: '🐱' }, desc: '一只神秘的小猫。', flavor: '第一个获得创世神的玩家。', formation: ['creator'] },
  { id: 'egg-rainbow-x', name: '炫彩幻蛋', rarity: 'rainbow', hidden: true, art: { type: 'egg', colors: 'rainbow' }, desc: '', flavor: '', formation: [] },
  { id: 'egg-zhenzhen', name: '珍珍蛋', rarity: 'white', art: { type: 'egg', colors: ['#FFD1DC', '#F5A9BE'] }, desc: '又高又圆的粉团子，说话软乎乎的。', flavor: '它察觉你心情不好，就会默默唱一首温柔的歌。', formation: ['egg-tongtong', 'egg-runrun'] },
  { id: 'egg-tongtong', name: '桐桐蛋', rarity: 'white', art: { type: 'egg', colors: ['#D0E7F5', '#9FC8E8'] }, desc: '镜框半垂的桐蛋，总在暗处憋住笑意。', flavor: '表面不动声色，肚子已经笑到发抖。', formation: ['egg-zhenzhen', 'egg-runrun'] },
  { id: 'egg-runrun', name: '润润蛋', rarity: 'white', art: { type: 'egg', colors: ['#C8B3E6', '#9E82CF'] }, desc: '无比神圣的蛋，比其他两个华丽许多。', flavor: '桐桐和珍珍的蛋妈。', formation: ['egg-zhenzhen', 'egg-tongtong'] },
  { id: 'moni', name: '莫尼', rarity: 'gold', art: { type: 'emoji', emoji: '🐱' }, desc: '莫尼是一只田园柯基猫，和狗融洽相处。', flavor: '“汪！”', formation: [] },
];

CARDS.forEach((c, i) => { c.no = i + 1; });

const CARD_MAP = {};
CARDS.forEach(c => { CARD_MAP[c.id] = c; });

const CONFIG = {
  VERSION: '1.13.0',
  INTERVAL_BASE: 10,
  INTERVAL_EXP: 0.4956,
  MIN_INTERVAL: 0.005,
  OFFLINE_CAP_HOURS: 8,
  FRAG_COST_PER_DRAW: 10,
  MAX_FRAG_DRAWS: 50000,
  SECRET_EGG_RATE: 1e-7,
  HOME_EGG_MIN: 900,
  HOME_EGG_MAX: 7200,
  HOME_EGG_BOOST: 0.5,
  SHINY_RATE: 0.00001,
  SHOP: {
    PITY: {
      purple: { baseCost: 50000, growth: 5 },
      gold: { baseCost: 800000, growth: 5 },
      black: { baseCost: 20000000, growth: 10 },
    },
    SPEEDUP_COST: 20000,
    SPEEDUP_MAX: 4,
    SPEEDUP_PCT: 0.25,
    NEST_SLOT_COSTS: [100000, 1000000, 10000000],
    COSMETIC_FRAME_COST: 100000,
  },
  ACHIEVEMENTS: [
    { id: 'pulls-100', name: '初出茅庐', desc: '累计抽卡 100 次', type: 'pulls', goal: 100, reward: 500 },
    { id: 'pulls-1000', name: '抽卡学徒', desc: '累计抽卡 1 千次', type: 'pulls', goal: 1000, reward: 5000 },
    { id: 'pulls-10000', name: '抽卡大师', desc: '累计抽卡 1 万次', type: 'pulls', goal: 10000, reward: 50000 },
    { id: 'kills-100', name: '猎蛋新手', desc: '累计击杀 100 只怪物', type: 'kills', goal: 100, reward: 500 },
    { id: 'clicks-100', name: '兔拉米拉米比啾豆', desc: '点击小怪兽 100 次', type: 'clicks', goal: 100, reward: 500 },
    { id: 'kills-5000', name: '猎蛋达人', desc: '累计击杀 5 千只怪物', type: 'kills', goal: 5000, reward: 10000 },
    { id: 'kills-50000', name: '猎蛋狂魔', desc: '累计击杀 5 万只怪物', type: 'kills', goal: 50000, reward: 100000 },
    { id: 'owned-20', name: '集卡入门', desc: '拥有 20 种卡片', type: 'owned', goal: 20, reward: 1000 },
    { id: 'owned-60', name: '集卡好手', desc: '拥有 60 种卡片', type: 'owned', goal: 60, reward: 3000 },
    { id: 'owned-100', name: '集卡大师', desc: '拥有 100 种卡片', type: 'owned', goal: 100, reward: 10000 },
    { id: 'owned-all', name: '全图鉴', desc: '拥有全部 ' + CARDS.filter(c => !c.hidden).length + ' 种卡片', type: 'owned', goal: CARDS.filter(c => !c.hidden).length, reward: 50000 },
    { id: 'rarity-purple', name: '紫霞初现', desc: '获得任意一张紫卡', type: 'rarity', goal: 'purple', reward: 1000 },
    { id: 'rarity-gold', name: '金光乍现', desc: '获得任意一张金卡', type: 'rarity', goal: 'gold', reward: 5000 },
    { id: 'rarity-black', name: '深渊凝视', desc: '获得任意一张黑卡', type: 'rarity', goal: 'black', reward: 500000 },
    { id: 'rarity-rainbow', name: '虹彩之巅', desc: '获得任意一张炫彩卡', type: 'rarity', goal: 'rainbow', reward: 1000000 },
    { id: 'power-1e4', name: '战力破万', desc: '当前出战编队战力达到 1 万', type: 'power', goal: 10000, reward: 10000 },
    { id: 'power-1e6', name: '战力百万', desc: '当前出战编队战力达到 100 万', type: 'power', goal: 1000000, reward: 100000 },
    { id: 'frags-10000', name: '碎片富翁', desc: '累计获得 1 万碎片', type: 'frags', goal: 10000, reward: 1000 },
    { id: 'offline-10000', name: '离线暴富', desc: '单次离线收益达到 1 万碎片', type: 'offline', goal: 10000, reward: 2000 },
    { id: 'nest-1', name: '宝宝出生了', desc: '开启第一枚蛋', type: 'nest', goal: 1, reward: 1000 },
    { id: 'secret-egg', name: '幻蛋之秘', desc: '触发神秘的炫彩幻蛋', type: 'secret', goal: 1, reward: 1000000 },
  ],
};
