const RARITIES = {
  white:   { name: '白卡',   order: 0, color: '#9ca3af', weight: 55,      basePower: 1,       frag: 1 },
green:   { name: '绿卡',   order: 1, color: '#16a34a', weight: 7.3,     basePower: 10,      frag: 2 },
  blue:    { name: '蓝卡',   order: 2, color: '#2563eb', weight: 2.5,     basePower: 20,      frag: 17 },
  purple:  { name: '紫卡',   order: 3, color: '#7c3aed', weight: 0.5,     basePower: 45,      frag: 85 },
  gold:    { name: '金卡',   order: 4, color: '#d97706', weight: 0.1,     basePower: 107,     frag: 425 },
  red:     { name: '红卡',   order: 5, color: '#dc2626', weight: 0.004,    basePower: 12000,   frag: 10628 },
  black:   { name: '黑卡',   order: 6, color: '#111827', weight: 0.0001,  basePower: 80000,   frag: 425127 },
  rainbow: { name: '炫彩卡', order: 7, color: 'rainbow', weight: 0.00002, basePower: 2000000, frag: 2125634 },
};

const RARITY_LIST = Object.keys(RARITIES).map(k => ({ id: k, ...RARITIES[k] })).sort((a, b) => a.order - b.order);

const CARDS = [
  { id: 'egg-rainbow',  name: '炫彩蛋',     rarity: 'white',  start: true, unique: true, art: { type: 'egg', colors: 'rainbow' },               desc: '传说中集齐五种元素之蛋才会孵化的神奇蛋。',                flavor: '它只是一颗白卡蛋，但梦想是炫彩的。',             formation: ['egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'egg-gold',     name: '金蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ffe9a8', '#f5b52e'] },  desc: '沉甸甸的蛋，隐约透出金光。',                              flavor: '晃一晃，里面有叮当声。',                        formation: [] },
  { id: 'egg-wood',     name: '木蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#e0d3b0', '#8a6b3f'] },  desc: '外壳带着树皮纹路的蛋。',                                  flavor: '插进土里好像会发芽。',                          formation: [] },
  { id: 'egg-water',    name: '水蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#d6ecff', '#4da3ff'] },  desc: '轻轻晃动，能听到水声的蛋。',                              flavor: '永远潮乎乎的。',                                formation: [] },
  { id: 'egg-fire',     name: '火蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ffe0cc', '#ff7a45'] },  desc: '摸上去热乎乎的蛋。',                                      flavor: '冬天抱着它睡觉。',                              formation: [] },
  { id: 'egg-earth',    name: '土蛋',       rarity: 'white',  start: true, art: { type: 'egg', colors: ['#ecd9b8', '#96704a'] },  desc: '沾着泥土气息的蛋。',                                      flavor: '重得像个哑铃。',                                formation: [] },
  { id: 'sapling',      name: '小树苗',     rarity: 'green',  art: { type: 'emoji', emoji: '🌱' },  desc: '需要三颗蛋的陪伴才能茁壮成长。',            flavor: '一天长一片叶子。',                              formation: ['egg-wood', 'egg-earth', 'egg-water'] },
  { id: 'ember',        name: '小火苗',     rarity: 'green',  art: { type: 'emoji', emoji: '🔥' },  desc: '一点就着的小脾气。',                        flavor: '吹口气就会灭。',                              formation: ['egg-fire', 'egg-wood', 'egg-gold'] },
  { id: 'droplet',      name: '小水灵',     rarity: 'green',  art: { type: 'emoji', emoji: '💧' },  desc: '整天咕嘟咕嘟冒泡。',                        flavor: '哭的时候会下雨。',                            formation: ['egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'forest-guard', name: '森林守卫',   rarity: 'blue',   art: { type: 'emoji', emoji: '🌳' },  desc: '森林里最可靠的伙伴。',                      flavor: '每一片叶子都在放哨。',                        formation: ['sapling', 'egg-wood', 'egg-earth'] },
  { id: 'lava-turtle',  name: '岩浆龟',     rarity: 'blue',   art: { type: 'emoji', emoji: '🐢' },  desc: '龟壳里住着一座小火山。',                    flavor: '走得慢，但挡不住。',                          formation: ['ember', 'egg-fire'] },
  { id: 'elementalist', name: '元素使',     rarity: 'purple', art: { type: 'emoji', emoji: '⚗️' },  desc: '调和水火木土的大师。',                      flavor: '配方是机密。',                                formation: ['egg-fire', 'egg-water', 'egg-wood', 'egg-earth'] },
  { id: 'rainbow-dragon', name: '彩虹龙',   rarity: 'gold',   art: { type: 'emoji', emoji: '🐉' },  desc: '横跨天际的传说之龙。',                      flavor: '它飞过的地方会下糖果雨。',                  formation: ['elementalist', 'forest-guard', 'lava-turtle', 'ember', 'droplet', 'sapling'] },
  { id: 'chaos-lord',   name: '混沌魔王',   rarity: 'red',    art: { type: 'emoji', emoji: '👹' },  desc: '吞噬光明与秩序。',                          flavor: '连影子都害怕它。',                            formation: ['rainbow-dragon', 'elementalist', 'egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'abyss-lord',   name: '深渊之主',   rarity: 'black',  art: { type: 'emoji', emoji: '🕳️' },  desc: '凝视深渊者，终将被深渊凝视。',              flavor: '没人见过它的真面目。',                        formation: ['chaos-lord', 'rainbow-dragon', 'elementalist', 'egg-gold', 'egg-wood', 'egg-water', 'egg-fire', 'egg-earth'] },
  { id: 'creator',      name: '创世神',     rarity: 'rainbow', art: { type: 'emoji', emoji: '✨' },  desc: '一切卡片的起源。',                          flavor: '它给自己写的登场台词。',                      formation: ['abyss-lord', 'chaos-lord', 'rainbow-dragon', 'elementalist'] },
  { id: 'egg-stone',    name: '石头蛋',     rarity: 'white',  art: { type: 'egg', colors: ['#e2e8f0', '#94a3b8'] },  desc: '重得像块石头的蛋。',                      flavor: '砸核桃挺好用。',                          formation: [] },
  { id: 'egg-thunder',  name: '雷蛋',       rarity: 'white',  art: { type: 'egg', colors: ['#fef9c3', '#eab308'] },  desc: '偶尔会噼啪作响的蛋。',                    flavor: '摸之前记得先洗手。',                      formation: [] },
  { id: 'egg-ice',      name: '冰蛋',       rarity: 'white',  art: { type: 'egg', colors: ['#e0f2fe', '#38bdf8'] },  desc: '摸起来凉飕飕的蛋。',                      flavor: '夏天想抱着它。',                          formation: [] },
  { id: 'rockling',     name: '小石头',     rarity: 'green',  art: { type: 'emoji', emoji: '🪨' },  desc: '一块会滚的小石头。',                      flavor: '滚起来比看起来快。',                      formation: ['egg-stone', 'egg-gold', 'egg-wood'] },
  { id: 'cloudling',    name: '小云朵',     rarity: 'green',  art: { type: 'emoji', emoji: '☁️' },  desc: '软绵绵的云朵精灵。',                      flavor: '心情好就下雨。',                          formation: ['egg-water', 'egg-thunder', 'egg-ice'] },
  { id: 'blossom',      name: '小花精',     rarity: 'green',  art: { type: 'emoji', emoji: '🌸' },  desc: '从花苞里钻出来的小家伙。',                flavor: '走到哪香到哪。',                          formation: ['egg-wood', 'egg-water', 'egg-earth'] },
  { id: 'thunder-spirit', name: '雷灵',     rarity: 'blue',   art: { type: 'emoji', emoji: '⚡' },  desc: '脾气火爆的电系精灵。',                    flavor: '打雷天最精神。',                          formation: ['cloudling', 'egg-thunder', 'egg-water'] },
  { id: 'ice-wisp',     name: '冰灵',       rarity: 'blue',   art: { type: 'emoji', emoji: '❄️' },  desc: '指尖掠过霜雪的精灵。',                    flavor: '夏天站在它身边很凉快。',                  formation: ['blossom', 'egg-ice', 'egg-wood'] },
  { id: 'rock-golem',   name: '岩甲兵',     rarity: 'blue',   art: { type: 'emoji', emoji: '🗿' },  desc: '岩石堆成的沉默士兵。',                    flavor: '它的笑点很低。',                          formation: ['rockling', 'egg-earth', 'egg-gold'] },
  { id: 'storm-witch',  name: '风暴女巫',   rarity: 'purple', art: { type: 'emoji', emoji: '🧙' },  desc: '把闪电装进帽子的女巫。',                  flavor: '帽子其实是晴雨计。',                      formation: ['thunder-spirit', 'cloudling', 'egg-thunder', 'egg-ice'] },
  { id: 'crystal-golem', name: '水晶魔像',  rarity: 'purple', art: { type: 'emoji', emoji: '💎' },  desc: '浑身剔透的水晶造物。',                    flavor: '在阳光下会闪瞎眼。',                      formation: ['rock-golem', 'ice-wisp', 'egg-ice', 'egg-gold'] },
  { id: 'thunder-dragon', name: '雷光龙',   rarity: 'gold',   art: { type: 'emoji', emoji: '🐲' },  desc: '御雷而行的东方之龙。',                    flavor: '尾巴一甩就是一道闪电。',                  formation: ['storm-witch', 'thunder-spirit', 'cloudling', 'ice-wisp', 'egg-thunder', 'egg-ice'] },
  { id: 'gold-golem',   name: '金晶王',     rarity: 'gold',   art: { type: 'emoji', emoji: '👑' },  desc: '统治矿物王国的黄金之王。',                flavor: '它的王座是块大金矿。',                    formation: ['crystal-golem', 'rock-golem', 'rockling', 'egg-gold', 'egg-wood', 'egg-earth'] },
  { id: 'storm-lord',   name: '风暴之主',   rarity: 'red',    art: { type: 'emoji', emoji: '🌩️' },  desc: '将整片天空握在手中。',                    flavor: '它一打喷嚏就会刮台风。',                  formation: ['thunder-dragon', 'storm-witch', 'gold-golem', 'egg-thunder', 'egg-gold'] },
  { id: 'void-dragon',  name: '虚空之龙',   rarity: 'black',  art: { type: 'emoji', emoji: '🌀' },  desc: '蛰伏于虚空尽头的古龙。',                  flavor: '它的叹息就是黑洞。',                      formation: ['storm-lord', 'thunder-dragon', 'gold-golem', 'crystal-golem', 'egg-thunder', 'egg-ice'] },
  { id: 'green-01', name: '碧使', rarity: 'green', art: { type: 'emoji', emoji: '🕯️' }, desc: '举着烛火巡夜的信使，天亮前绝不眨眼。', flavor: '烛芯是它珍藏的一根草茎。', formation: ['sapling', 'ember', 'blossom'] },
  { id: 'green-02', name: '蒲学徒', rarity: 'green', art: { type: 'emoji', emoji: '🌌' }, desc: '趴在草尖上数星星的学徒，数到 99 就会睡着。', flavor: '星星的数目每晚都变，它记了三年账。', formation: ['cloudling', 'blossom'] },
  { id: 'green-03', name: '柳使', rarity: 'green', art: { type: 'emoji', emoji: '🍃' }, desc: '顶着伞盖躲雨的柳使，雨停也不肯收伞。', flavor: '伞下藏着三颗松果，是它的存粮。', formation: ['rockling', 'green-01', 'ember'] },
  { id: 'green-04', name: '蔓仆', rarity: 'green', art: { type: 'emoji', emoji: '🍀' }, desc: '用藤蔓编花环的蔓仆，手比名字巧十倍。', flavor: '编坏的花环它都留着，说是历史。', formation: ['green-03', 'blossom'] },
  { id: 'green-05', name: '果精灵', rarity: 'green', art: { type: 'emoji', emoji: '🍎' }, desc: '守着果林第一枚果实的精灵，谁先咬谁挨嚎。', flavor: '嚎声是吓鸟的，不是真凶。', formation: ['blossom', 'rockling'] },
  { id: 'green-06', name: '芽仆', rarity: 'green', art: { type: 'emoji', emoji: '🫘' }, desc: '把每颗种子当孩子盯的芽仆，风雨无阻。', flavor: '它吼声很响，其实怕蜜蜂。', formation: ['rockling', 'green-02', 'blossom'] },
  { id: 'green-07', name: '芽芽', rarity: 'green', art: { type: 'emoji', emoji: '🪴' }, desc: '破土时只有拇指大，现在还是拇指大。', flavor: '它坚信自己迟早长成大树。', formation: ['sapling', 'cloudling', 'green-04'] },
  { id: 'green-08', name: '苔童', rarity: 'green', art: { type: 'emoji', emoji: '🍄' }, desc: '在石缝间穿行的小苔童，走路悄无声息。', flavor: '脚底的绿毯是它自己种的。', formation: ['green-01', 'green-05', 'sapling'] },
  { id: 'green-09', name: '蔓芽', rarity: 'green', art: { type: 'emoji', emoji: '🌵' }, desc: '从火山灰里钻出的芽，叶尖烫手。', flavor: '冒烟是在生闷气，浇水就好。', formation: ['sapling', 'green-03'] },
  { id: 'green-10', name: '竹祭司', rarity: 'green', art: { type: 'emoji', emoji: '🎋' }, desc: '用竹节占卜天气的祭司，十占九不准。', flavor: '不准的时候它说是风向的错。', formation: ['blossom', 'droplet', 'green-05'] },
  { id: 'green-11', name: '松族', rarity: 'green', art: { type: 'emoji', emoji: '🌰' }, desc: '把松果当钱币攒的松族，只进不出。', flavor: '小金库在树洞里，钥匙是根羽毛。', formation: ['green-02', 'blossom', 'droplet'] },
  { id: 'green-12', name: '青卫', rarity: 'green', art: { type: 'emoji', emoji: '🦊' }, desc: '在林间巡逻的青卫，尾巴竖着当旗。', flavor: '它记仇记恩都刻在石头上。', formation: ['green-11', 'green-06'] },
  { id: 'green-13', name: '苍卫', rarity: 'green', art: { type: 'emoji', emoji: '🦉' }, desc: '蹲在溪边看虫子的苍卫，一看一整天。', flavor: '每条虫它都给取了名字。', formation: ['green-06', 'ember', 'cloudling'] },
  { id: 'green-14', name: '竹姬', rarity: 'green', art: { type: 'emoji', emoji: '🎍' }, desc: '竹节里住着的公主，敲三下竹竿她开花。', flavor: '她一笑，整片竹林跟着晃。', formation: ['green-02', 'green-04', 'cloudling'] },
  { id: 'green-15', name: '苔姬', rarity: 'green', art: { type: 'emoji', emoji: '🌿' }, desc: '披着绿斗篷的苔姬，走到哪绿到哪。', flavor: '她的裙摆是活的草坪。', formation: ['ember', 'green-12', 'cloudling'] },
  { id: 'green-16', name: '蒲祭司', rarity: 'green', art: { type: 'emoji', emoji: '🌼' }, desc: '举蒲公英给迷路者指路的祭司。', flavor: '指错方向时，它说这是命运。', formation: ['green-04', 'green-05', 'green-12'] },
  { id: 'blue-01', name: '泉灵', rarity: 'blue', art: { type: 'emoji', emoji: '🧿' }, desc: '泉眼深处睁着眼睛的灵，眨一下泉水就冒泡。', flavor: '它数得清每滴水回湖的路。', formation: ['thunder-spirit', 'lava-turtle', 'sapling'] },
  { id: 'blue-02', name: '雾士', rarity: 'blue', art: { type: 'emoji', emoji: '🌫️' }, desc: '晨雾里站岗的士，太阳出来就下班。', flavor: '它的制服是露水做的，晒晒就干。', formation: ['lava-turtle', 'sapling'] },
  { id: 'blue-03', name: '雪灵', rarity: 'blue', art: { type: 'emoji', emoji: '🌨️' }, desc: '雪堆里打滚的灵体，指尖一碰就化。', flavor: '它怕热，但更怕没人陪它堆雪人。', formation: ['blue-01', 'rockling'] },
  { id: 'blue-04', name: '澜使', rarity: 'blue', art: { type: 'emoji', emoji: '🌊' }, desc: '踏浪尖送信的使者，信封从不上潮。', flavor: '它的信封是贝壳，邮戳是水花。', formation: ['blue-03', 'blossom'] },
  { id: 'blue-05', name: '澜龙', rarity: 'blue', art: { type: 'emoji', emoji: '🐊' }, desc: '把湖面当镜子照的澜龙，发型不能乱。', flavor: '它教青蛙游泳，青蛙学会了潜泳。', formation: ['thunder-spirit', 'blue-04', 'rockling', 'blossom'] },
  { id: 'blue-06', name: '湖蟹', rarity: 'blue', art: { type: 'emoji', emoji: '🦀' }, desc: '横着走的湖蟹，钳子里夹着湖底机密。', flavor: '机密只有一条：湖底全是泥。', formation: ['blue-04', 'blue-01', 'droplet'] },
  { id: 'blue-07', name: '波精', rarity: 'blue', art: { type: 'emoji', emoji: '💦' }, desc: '收集涟漪当收藏品的波精，一格一枚。', flavor: '最贵的一枚，是蜻蜓点水的。', formation: ['blue-04', 'ice-wisp', 'sapling'] },
  { id: 'blue-08', name: '雪卫', rarity: 'blue', art: { type: 'emoji', emoji: '🐼' }, desc: '守在冰缘的雪卫，从不让自己打滑。', flavor: '它让每片雪都落得整整齐齐。', formation: ['blue-07', 'ember', 'droplet'] },
  { id: 'blue-09', name: '冰兽', rarity: 'blue', art: { type: 'emoji', emoji: '🦣' }, desc: '背着冰壳的兽，呼吸喷白雾。', flavor: '它打喷嚏能冻半条河，所以忍着。', formation: ['blue-06', 'ember'] },
  { id: 'blue-10', name: '瀑使', rarity: 'blue', art: { type: 'emoji', emoji: '⛲' }, desc: '把瀑布拧成绳子的瀑使，力大无穷。', flavor: '拧出的水绳，能晾一山的衣裳。', formation: ['blue-01', 'blue-03', 'cloudling', 'droplet'] },
  { id: 'blue-11', name: '波师', rarity: 'blue', art: { type: 'emoji', emoji: '📖' }, desc: '研究水波的老师，讲课从来不用稿。', flavor: '它说水波是唯一听讲的学生。', formation: ['forest-guard', 'rock-golem', 'sapling'] },
  { id: 'blue-12', name: '湖鲸', rarity: 'blue', art: { type: 'emoji', emoji: '🐋' }, desc: '沉在湖底的鲸，背上盖着一座小城。', flavor: '它浮上来，是为了换一座城。', formation: ['blue-03', 'blue-05', 'ember'] },
  { id: 'blue-13', name: '澜兽', rarity: 'blue', art: { type: 'emoji', emoji: '🦌' }, desc: '四蹄踏水不沉的澜兽，跑起来像一堵浪。', flavor: '它踩出的涟漪十年不散。', formation: ['lava-turtle', 'rockling', 'sapling'] },
  { id: 'blue-14', name: '渊龙', rarity: 'blue', art: { type: 'emoji', emoji: '🐍' }, desc: '盘在深水的渊龙，鳞片剪开月光。', flavor: '它不上浮，除非有人讲笑话。', formation: ['blue-10', 'blue-05', 'rockling', 'sapling'] },
  { id: 'blue-15', name: '湖士', rarity: 'blue', art: { type: 'emoji', emoji: '🐡' }, desc: '一被夸奖就膨胀的湖士，胀成球弹走。', flavor: '它弹走的方向，总是朝着夸奖声。', formation: ['blue-13', 'blue-08', 'ember', 'droplet'] },
  { id: 'blue-16', name: '瀑鲛', rarity: 'blue', art: { type: 'emoji', emoji: '⚒️' }, desc: '在瀑布里打铁的鲛人，锤声如雷。', flavor: '它打的铁器，连河水都喜欢。', formation: ['lava-turtle', 'ember', 'rockling'] },
  { id: 'purple-01', name: '魅将', rarity: 'purple', art: { type: 'emoji', emoji: '🧜' }, desc: '魅惑之术师从海巫，歌声能定潮汐。', flavor: '它的咒语押韵，失败也押韵。', formation: ['storm-witch', 'elementalist', 'lava-turtle'] },
  { id: 'purple-02', name: '辰伯爵', rarity: 'purple', art: { type: 'emoji', emoji: '🎩' }, desc: '领口永远立着的伯爵，怕冷也怕打雷。', flavor: '雷雨天它躲在最厚的书后面。', formation: ['storm-witch', 'purple-01', 'forest-guard', 'ice-wisp'] },
  { id: 'purple-03', name: '星术士', rarity: 'purple', art: { type: 'emoji', emoji: '🔭' }, desc: '挎着星图篮子的术士，摘星当晚餐。', flavor: '篮子里的星星到早晨就化了。', formation: ['purple-01', 'forest-guard'] },
  { id: 'purple-04', name: '魅伯爵', rarity: 'purple', art: { type: 'emoji', emoji: '🦾' }, desc: '铁臂伯爵，握手时从不使力。', flavor: '它那双手其实是借来的。', formation: ['crystal-golem', 'purple-03', 'rock-golem', 'thunder-spirit'] },
  { id: 'purple-05', name: '影术士', rarity: 'purple', art: { type: 'emoji', emoji: '🗡️' }, desc: '把影子削成匕首的术士，出鞘无声。', flavor: '它从不背对光。', formation: ['purple-02', 'purple-03', 'lava-turtle'] },
  { id: 'purple-06', name: '夜爵', rarity: 'purple', art: { type: 'emoji', emoji: '🦎' }, desc: '贴着墙根行走的夜爵，像一片会喘气的影子。', flavor: '它断掉的尾巴，第二天长回来。', formation: ['crystal-golem', 'purple-02', 'forest-guard'] },
  { id: 'purple-07', name: '梦巫师', rarity: 'purple', art: { type: 'emoji', emoji: '🐑' }, desc: '数羊入眠的巫师，数到第一千只会被羊叫醒。', flavor: '它卖的梦，签收要按手印。', formation: ['purple-02', 'ice-wisp'] },
  { id: 'purple-08', name: '冥侯', rarity: 'purple', art: { type: 'emoji', emoji: '🪓' }, desc: '挥斧劈开夜色的冥侯，斧刃从来不锈。', flavor: '它说斧头比月亮勤快。', formation: ['purple-04', 'ice-wisp'] },
  { id: 'purple-09', name: '月巫师', rarity: 'purple', art: { type: 'emoji', emoji: '🐸' }, desc: '月光下施法的巫师，蟾蜍是它的坐骑。', flavor: '它念咒，坐骑打嗝，咒语就破了。', formation: ['purple-04', 'ice-wisp', 'rock-golem'] },
  { id: 'purple-10', name: '月爵', rarity: 'purple', art: { type: 'emoji', emoji: '🧝' }, desc: '精灵血统的月爵，耳朵尖得像月牙。', flavor: '它听得到花瓣落地的声音。', formation: ['storm-witch', 'lava-turtle'] },
  { id: 'purple-11', name: '夜将', rarity: 'purple', art: { type: 'emoji', emoji: '🌙' }, desc: '夜巡的将军，披风是藤蔓织的。', flavor: '它走过的地方，第二天冒新芽。', formation: ['purple-07', 'ice-wisp', 'rock-golem'] },
  { id: 'purple-12', name: '夜司祭', rarity: 'purple', art: { type: 'emoji', emoji: '🐳' }, desc: '深海唱诗班的司祭，嗓音低沉如鲸。', flavor: '它的祷词能让海面平静。', formation: ['purple-05', 'purple-09', 'lava-turtle'] },
  { id: 'purple-13', name: '辰爵', rarity: 'purple', art: { type: 'emoji', emoji: '🌅' }, desc: '黎明前上岗的辰爵，抱着钟楼打盹。', flavor: '它误点的钟声，大家都不怪它。', formation: ['purple-03', 'forest-guard'] },
  { id: 'purple-14', name: '暮侯', rarity: 'purple', art: { type: 'emoji', emoji: '🪶' }, desc: '黄昏收集羽毛的侯爵，帽子上插满鸟羽。', flavor: '每根羽毛它都记得是谁掉的。', formation: ['purple-02', 'purple-05', 'ice-wisp'] },
  { id: 'purple-15', name: '暮骑', rarity: 'purple', art: { type: 'emoji', emoji: '🦢' }, desc: '骑着天鹅巡逻的暮骑，披风是晚霞。', flavor: '它从不参加晨会。', formation: ['purple-14', 'thunder-spirit'] },
  { id: 'purple-16', name: '夜祭司', rarity: 'purple', art: { type: 'emoji', emoji: '⭐' }, desc: '给迷途者指星的祭司，指哪颗哪颗亮。', flavor: '它从不迷路，它说星星认得它。', formation: ['storm-witch', 'purple-06', 'rock-golem', 'thunder-spirit'] },
  { id: 'gold-01', name: '冠爵', rarity: 'gold', art: { type: 'emoji', emoji: '⛏️' }, desc: '矿脉中诞生的爵爷，王冠是铁镐改的。', flavor: '它说权力会生锈，所以常磨。', formation: ['thunder-dragon', 'crystal-golem'] },
  { id: 'gold-02', name: '虎王', rarity: 'gold', art: { type: 'emoji', emoji: '🐯' }, desc: '虎纹陶罐里醒来的王，一吼山门开。', flavor: '它吃早餐时要铺餐巾。', formation: ['thunder-dragon', 'elementalist', 'crystal-golem'] },
  { id: 'gold-03', name: '鸾宰相', rarity: 'gold', art: { type: 'emoji', emoji: '🧪' }, desc: '炼金术出身的宰相，奏折是配方。', flavor: '它的计谋都带一点点药味。', formation: ['gold-golem', 'storm-witch', 'elementalist'] },
  { id: 'gold-04', name: '君元帅', rarity: 'gold', art: { type: 'emoji', emoji: '⚜️' }, desc: '盾徽镶金的元帅，凯旋也要按军礼。', flavor: '它给每位士兵都留了位置。', formation: ['gold-02', 'rainbow-dragon', 'storm-witch'] },
  { id: 'gold-05', name: '豹爵', rarity: 'gold', art: { type: 'emoji', emoji: '🐆' }, desc: '踩着晚霞巡山的豹爵，步子像鼓点。', flavor: '它的领地日落时最好看。', formation: ['gold-golem', 'elementalist', 'storm-witch'] },
  { id: 'gold-06', name: '鹤将军', rarity: 'gold', art: { type: 'emoji', emoji: '🦩' }, desc: '白头鹤将军，塔楼顶就是它的瞭望台。', flavor: '它低头是为了看清谁在敬礼。', formation: ['gold-05', 'gold-golem', 'storm-witch'] },
  { id: 'gold-07', name: '贤元帅', rarity: 'gold', art: { type: 'emoji', emoji: '🗿' }, desc: '石像里走出的元帅，军令刻在额上。', flavor: '它站岗时，连风都要绕路。', formation: ['gold-01', 'gold-02', 'elementalist', 'crystal-golem'] },
  { id: 'gold-08', name: '鹤王', rarity: 'gold', art: { type: 'emoji', emoji: '🦅' }, desc: '朱顶鹤王，翎羽沾着夕阳的血色。', flavor: '它一展翅，半边天都红了。', formation: ['gold-05', 'rainbow-dragon', 'crystal-golem', 'storm-witch'] },
  { id: 'gold-09', name: '鸾元帅', rarity: 'gold', art: { type: 'emoji', emoji: '🦚' }, desc: '披星执剑的鸾元帅，剑鞘缀着彗尾。', flavor: '它拔剑的速度比流星快。', formation: ['gold-04', 'gold-07', 'storm-witch'] },
  { id: 'gold-10', name: '麟预言家', rarity: 'gold', art: { type: 'emoji', emoji: '🦄' }, desc: '踏浪而行的麟预言家，浪尖写满签文。', flavor: '它预言过海啸，也预言过晴日。', formation: ['gold-05', 'elementalist'] },
  { id: 'gold-11', name: '豹君主', rarity: 'gold', art: { type: 'emoji', emoji: '🦐' }, desc: '虾钳王座的君主，钳子镀了金。', flavor: '它敲三下王座，潮水就退。', formation: ['thunder-dragon', 'elementalist'] },
  { id: 'gold-12', name: '麟宰相', rarity: 'gold', art: { type: 'emoji', emoji: '🐎' }, desc: '袖中藏花的宰相，谈判桌上花比话多。', flavor: '它送出去的花都另有深意。', formation: ['thunder-dragon', 'gold-01', 'elementalist', 'storm-witch'] },
  { id: 'gold-13', name: '冠预言家', rarity: 'gold', art: { type: 'emoji', emoji: '🪐' }, desc: '星环缠身的预言家，句句带光环。', flavor: '它预言自己明天也会预言。', formation: ['rainbow-dragon', 'gold-golem', 'elementalist', 'storm-witch'] },
  { id: 'gold-14', name: '傲祭司', rarity: 'gold', art: { type: 'emoji', emoji: '🐄' }, desc: '牛角祭坛的祭司，布道声如闷雷。', flavor: '它的信徒是整片牧场。', formation: ['gold-10', 'gold-13', 'crystal-golem'] },
  { id: 'gold-15', name: '权宰相', rarity: 'gold', art: { type: 'emoji', emoji: '📜' }, desc: '权杖嵌钻的宰相，说话自带回音。', flavor: '它点头，国库就响一声。', formation: ['thunder-dragon', 'storm-witch', 'elementalist'] },
  { id: 'gold-16', name: '皇骑士长', rarity: 'gold', art: { type: 'emoji', emoji: '🔮' }, desc: '水晶球当盾的骑士长，能看见三秒后。', flavor: '它总说：我早知道了，但谢谢。', formation: ['gold-03', 'crystal-golem', 'storm-witch'] },
  { id: 'red-01', name: '魔尊', rarity: 'red', art: { type: 'emoji', emoji: '🪄' }, desc: '魔杖所指皆成焦土的尊上，从不说第二遍。', flavor: '它唯一的软肋是怕冷。', formation: ['chaos-lord', 'storm-lord', 'gold-golem', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-02', name: '焚魔王', rarity: 'red', art: { type: 'emoji', emoji: '⚱️' }, desc: '骨灰瓮里重生的魔王，点火不用打火石。', flavor: '它睡觉时床铺是温的。', formation: ['chaos-lord', 'storm-lord', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-03', name: '蚀主', rarity: 'red', art: { type: 'emoji', emoji: '🤖' }, desc: '吞吃岩石的机械之主，齿轮就是牙齿。', flavor: '它锈了会下雨，雨就是机油。', formation: ['storm-lord', 'red-02', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-04', name: '灭帝', rarity: 'red', art: { type: 'emoji', emoji: '💥' }, desc: '一脚踏平城邦的灭帝，落地从不回头。', flavor: '它踩过的地方，草长得特别高。', formation: ['red-01', 'storm-lord', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-05', name: '厄暴君', rarity: 'red', art: { type: 'emoji', emoji: '👽' }, desc: '来自星外的暴君，瞳孔是裂缝。', flavor: '它数不清地球的月亮有几个。', formation: ['storm-lord', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-06', name: '邪收割者', rarity: 'red', art: { type: 'emoji', emoji: '🌾' }, desc: '日出时收魂的收割者，镰刀镀着晨光。', flavor: '它其实想改行种麦子。', formation: ['red-05', 'red-03', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-07', name: '血吞噬者', rarity: 'red', art: { type: 'emoji', emoji: '🐈' }, desc: '舔干净血迹的吞噬者，像一只大猫。', flavor: '它打盹时呼噜声像雷。', formation: ['red-01', 'rainbow-dragon', 'thunder-dragon'] },
  { id: 'red-08', name: '恶尊', rarity: 'red', art: { type: 'emoji', emoji: '🦝' }, desc: '偷走月光的恶尊，赃物藏在树洞。', flavor: '每月十五它去月下补赃。', formation: ['red-02', 'thunder-dragon', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-09', name: '血圣', rarity: 'red', art: { type: 'emoji', emoji: '🦖' }, desc: '远古血脉的圣兽，鳞片渗着岩浆。', flavor: '它吼一声，火山跟着咳嗽。', formation: ['red-06', 'rainbow-dragon', 'gold-golem', 'thunder-dragon'] },
  { id: 'red-10', name: '湮大公', rarity: 'red', art: { type: 'emoji', emoji: '🪝' }, desc: '钩走一切的大公，钩子上什么都能挂。', flavor: '它钓过一条彩虹，放生了。', formation: ['red-04', 'red-03', 'rainbow-dragon', 'thunder-dragon', 'gold-golem'] },
  { id: 'red-11', name: '恨神', rarity: 'red', art: { type: 'emoji', emoji: '🦤' }, desc: '灭绝名单上的恨神，爪子握紧不放。', flavor: '它恨一切，除了打盹。', formation: ['red-03', 'chaos-lord', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-12', name: '灾收割者', rarity: 'red', art: { type: 'emoji', emoji: '🎒' }, desc: '背着灾袋的收割者，撒豆成祸。', flavor: '它的布袋漏了，灾就小了。', formation: ['red-03', 'thunder-dragon', 'rainbow-dragon', 'gold-golem'] },
  { id: 'red-13', name: '灭魔王', rarity: 'red', art: { type: 'emoji', emoji: '🐝' }, desc: '蜂群组成的魔王，散则蜂聚则王。', flavor: '它的蜂针是言出法随。', formation: ['red-09', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-14', name: '怨神', rarity: 'red', art: { type: 'emoji', emoji: '🧛' }, desc: '吸食怨气的古神，怨气当茶饮。', flavor: '它品得出每杯怨气的产地。', formation: ['red-01', 'rainbow-dragon', 'thunder-dragon', 'gold-golem'] },
  { id: 'red-15', name: '恶帝', rarity: 'red', art: { type: 'emoji', emoji: '🐹' }, desc: '鼠面恶帝，朝堂设在粮仓顶上。', flavor: '它批奏折时啃胡萝卜。', formation: ['chaos-lord', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-16', name: '邪主宰', rarity: 'red', art: { type: 'emoji', emoji: '🥀' }, desc: '花瓣染血的邪主宰，美得让人不敢看。', flavor: '它落泪的地方开出血色花。', formation: ['red-15', 'red-09', 'thunder-dragon', 'gold-golem', 'rainbow-dragon'] },
  { id: 'red-17', name: '灾君', rarity: 'red', art: { type: 'emoji', emoji: '👁️' }, desc: '全知之眼只睁一半的灾君。', flavor: '它闭眼时，坏事都在路上。', formation: ['red-02', 'gold-golem', 'thunder-dragon', 'rainbow-dragon'] },
  { id: 'red-18', name: '厄狱长', rarity: 'red', art: { type: 'emoji', emoji: '⛄' }, desc: '冰狱的狱长，钥匙串在雪人身上。', flavor: '它不放任何人走，包括春天。', formation: ['red-14', 'red-03', 'gold-golem', 'rainbow-dragon'] },
  { id: 'black-01', name: '恒归墟', rarity: 'black', art: { type: 'emoji', emoji: '🦆' }, desc: '从归墟浮起的黑鸭，翅膀遮天。', flavor: '它凫水的地方，星海起皱。', formation: ['void-dragon', 'abyss-lord', 'chaos-lord', 'storm-lord'] },
  { id: 'black-02', name: '万天尊', rarity: 'black', art: { type: 'emoji', emoji: '🦴' }, desc: '骨头拼成的天尊，指节拨动星河。', flavor: '它身上的每一根骨都叫过别的名字。', formation: ['black-01', 'abyss-lord', 'void-dragon', 'chaos-lord'] },
  { id: 'black-03', name: '太造物', rarity: 'black', art: { type: 'emoji', emoji: '🐗' }, desc: '创世野猪，獠牙犁开混沌。', flavor: '它拱出来的土，成了山。', formation: ['abyss-lord', 'void-dragon', 'black-01', 'chaos-lord', 'storm-lord'] },
  { id: 'black-04', name: '古天尊', rarity: 'black', art: { type: 'emoji', emoji: '🦕' }, desc: '背着纪元的古天尊，壳上刻满历法。', flavor: '它每走一步，世间过一纪。', formation: ['black-02', 'void-dragon', 'chaos-lord'] },
  { id: 'black-05', name: '虚道祖', rarity: 'black', art: { type: 'emoji', emoji: '🪸' }, desc: '珊瑚长成的道祖，触须触及虚空。', flavor: '它盘坐的地方，海底长出道场。', formation: ['black-03', 'void-dragon', 'black-01', 'storm-lord'] },
  { id: 'black-06', name: '古终焉', rarity: 'black', art: { type: 'emoji', emoji: '🐨' }, desc: '抱着末日树懒，动作慢到时间愿意等。', flavor: '它的缓慢是宇宙唯一的秩序。', formation: ['black-04', 'black-03', 'abyss-lord', 'void-dragon', 'chaos-lord'] },
  { id: 'black-07', name: '万寂灭', rarity: 'black', art: { type: 'emoji', emoji: '⚔️' }, desc: '剑锋所指皆归寂灭的武者。', flavor: '它出剑时，连回音都先死。', formation: ['black-02', 'black-05', 'chaos-lord'] },
  { id: 'black-08', name: '万古神', rarity: 'black', art: { type: 'emoji', emoji: '🌺' }, desc: '花开花落即万古的神，花瓣是纪元。', flavor: '它一转身，花期刚好一亿年。', formation: ['black-02', 'abyss-lord', 'black-03', 'black-06', 'chaos-lord', 'storm-lord'] },
  { id: 'black-09', name: '终道祖', rarity: 'black', art: { type: 'emoji', emoji: '🦦' }, desc: '在水面打坐的道祖，波纹是道纹。', flavor: '它睁眼，水面上映着三千世界。', formation: ['black-02', 'black-04', 'chaos-lord'] },
  { id: 'black-10', name: '永太初', rarity: 'black', art: { type: 'emoji', emoji: '🦗' }, desc: '第一声蝉鸣化成的太初。', flavor: '它的叫声比宇宙还早一瞬。', formation: ['black-02', 'black-03', 'storm-lord'] },
  { id: 'black-11', name: '始轮回', rarity: 'black', art: { type: 'emoji', emoji: '📿' }, desc: '拨动轮回念珠的始祖，一串 108 界。', flavor: '它拨错一颗，就多出一世。', formation: ['black-02', 'abyss-lord', 'black-03', 'black-04', 'storm-lord'] },
  { id: 'black-12', name: '归归墟', rarity: 'black', art: { type: 'emoji', emoji: '🧊' }, desc: '极寒中走向归墟的冰旅者。', flavor: '它脚印里的冰，万年不化。', formation: ['black-04', 'black-01', 'chaos-lord', 'storm-lord'] },
  { id: 'black-13', name: '太墓主', rarity: 'black', art: { type: 'emoji', emoji: '🦑' }, desc: '章鱼触手把守的墓主，墓门是漩涡。', flavor: '它守的不是尸骨，是没人记得的名字。', formation: ['black-12', 'black-07', 'chaos-lord', 'storm-lord'] },
  { id: 'black-14', name: '亘虚无', rarity: 'black', art: { type: 'emoji', emoji: '🗝️' }, desc: '钥匙悬在虚无里的存在，锁孔在万有。', flavor: '它开过的门，都忘记自己有门。', formation: ['black-09', 'black-12', 'storm-lord', 'chaos-lord'] },
  { id: 'black-15', name: '虚寂灭', rarity: 'black', art: { type: 'emoji', emoji: '🐂' }, desc: '牛角抵住寂灭的虚影，一步一虚。', flavor: '它走过的地方，声音都认输。', formation: ['black-04', 'black-11', 'black-03', 'storm-lord'] },
  { id: 'black-16', name: '亘天尊', rarity: 'black', art: { type: 'emoji', emoji: '🐰' }, desc: '月宫玉兔演化成的天尊，捣药声震星河。', flavor: '它捣的不是药，是时间。', formation: ['black-09', 'black-05', 'black-12', 'black-13', 'chaos-lord'] },
  { id: 'black-17', name: '无造物', rarity: 'black', art: { type: 'emoji', emoji: '🦫' }, desc: '用倒影筑坝的造物，坝拦的是因果。', flavor: '它咬断的木头，落水即成舟。', formation: ['black-02', 'black-14', 'black-05', 'storm-lord'] },
{ id: 'black-18', name: '玄太初', rarity: 'black', art: { type: 'emoji', emoji: '⚖️' }, desc: '称量一切的玄天秤，两头是天平。', flavor: '它称过太阳，八两。', formation: ['black-09', 'black-02', 'black-10', 'storm-lord', 'chaos-lord'] },
  { id: 'qinghuan-miao', name: '晴幻喵', rarity: 'rainbow', art: { type: 'emoji', emoji: '🐱' }, desc: '一只神秘的小猫。', flavor: '第一个获得创世神的玩家。', formation: ['creator'] },
  { id: 'egg-rainbow-x', name: '炫彩幻蛋', rarity: 'rainbow', hidden: true, art: { type: 'egg', colors: 'rainbow' }, desc: '', flavor: '', formation: [] },
  { id: 'egg-zhenzhen', name: '珍珍蛋', rarity: 'white', art: { type: 'egg', colors: ['#FFD1DC', '#F5A9BE'] }, desc: '又高又圆的粉团子，说话软乎乎的。', flavor: '它察觉你心情不好，就会默默唱一首温柔的歌。', formation: ['egg-tongtong', 'egg-runrun'] },
  { id: 'egg-tongtong', name: '桐桐蛋', rarity: 'white', art: { type: 'egg', colors: ['#D0E7F5', '#9FC8E8'] }, desc: '镜框半垂的桐蛋，总在暗处憋住笑意。', flavor: '表面不动声色，肚子已经笑到发抖。', formation: ['egg-zhenzhen', 'egg-runrun'] },
  { id: 'egg-runrun', name: '润润蛋', rarity: 'white', art: { type: 'egg', colors: ['#C8B3E6', '#9E82CF'] }, desc: '无比神圣的蛋，比其他两个华丽许多。', flavor: '桐桐和珍珍的蛋妈。', formation: ['egg-zhenzhen', 'egg-tongtong'] },
  { id: 'moni', name: '莫尼', rarity: 'gold', art: { type: 'emoji', emoji: '🐱' }, desc: '莫尼是一只田园柯基猫，和狗融洽相处。', flavor: '“汪！”', formation: [] },
  { id: 'g2-tetro-block', name: '方块蛋', rarity: 'white', art: { type: 'egg', colors: ['#dbeafe', '#60a5fa'] }, desc: '天生四四方方的蛋，拼起来刚好是一块。', flavor: '它数数只会数到四，五是不存在的。', formation: ['g2-tetro-line', 'g2-tetro-square', 'g2-tetro-clear'] },
  { id: 'g2-tetro-line', name: '长条', rarity: 'blue', art: { type: 'emoji', emoji: '📏' }, desc: '横着躺是地板，竖起来是柱子，就是不转弯。', flavor: '它拒绝斜着走，理由很充分。', formation: ['g2-tetro-block', 'g2-tetro-square', 'g2-tetro-clear'] },
  { id: 'g2-tetro-square', name: '方块', rarity: 'green', art: { type: 'emoji', emoji: '🟪' }, desc: '稳稳当当的方块，从不出格。', flavor: '它的证件照是正面拍的。', formation: ['g2-tetro-block', 'g2-tetro-line', 'g2-tetro-clear'] },
  { id: 'g2-tetro-clear', name: '消行师', rarity: 'gold', art: { type: 'emoji', emoji: '🧹' }, desc: '看到一排整齐就忍不住清掉，手痒。', flavor: '它的成就感来自那一声轰。', formation: ['g2-tetro-block', 'g2-tetro-line', 'g2-tetro-square'] },
  { id: 'g2-pac-coin', name: '街机蛋', rarity: 'white', art: { type: 'egg', colors: ['#fde68a', '#f59e0b'] }, desc: '吞硬币下蛋的老街机，投币才肯孵。', flavor: '它只认一种早就停产的硬币。', formation: ['g2-pac-dot', 'g2-pac-ghost'] },
  { id: 'g2-pac-dot', name: '圆吞鬼', rarity: 'green', art: { type: 'emoji', emoji: '🟡' }, desc: '走直线不吃辣的圆球，迷宫只走一条道。', flavor: '它追你的时候速度会翻倍。', formation: ['g2-pac-coin', 'g2-pac-ghost'] },
  { id: 'g2-pac-ghost', name: '追尾鬼', rarity: 'purple', art: { type: 'emoji', emoji: '👻' }, desc: '贴墙游荡的幽灵，眼睛会发光。', flavor: '它怕了一颗蓝色的大力丸。', formation: ['g2-pac-coin', 'g2-pac-dot'] },
  { id: 'g2-snake-apple', name: '蛇果蛋', rarity: 'white', art: { type: 'egg', colors: ['#fecaca', '#ef4444'] }, desc: '红得像顿晚餐的蛋，碰一下就会消失。', flavor: '它知道所有假果子的位置。', formation: ['g2-snake-body'] },
  { id: 'g2-snake-body', name: '蛇精', rarity: 'green', art: { type: 'emoji', emoji: '🐍' }, desc: '越吃越长的蛇，吃一颗果子长一寸。', flavor: '它撞到自己尾巴的时候最懊恼。', formation: ['g2-snake-apple'] },
  { id: 'g2-mario-star', name: '星星蛋', rarity: 'white', art: { type: 'egg', colors: ['#fef9c3', '#facc15'] }, desc: '金黄色的蛋，跳三下会发光。', flavor: '它转圈的时候谁都打不到它。', formation: ['g2-mario-plumber', 'g2-mario-mushroom', 'g2-mario-coin', 'g2-mario-princess', 'g2-mario-bowser'] },
  { id: 'g2-mario-plumber', name: '水管工', rarity: 'green', art: { type: 'emoji', emoji: '👷' }, desc: '红帽子蓝裤子的修理工，专钻水管。', flavor: '它跳起来能顶碎砖块。', formation: ['g2-mario-star', 'g2-mario-mushroom', 'g2-mario-coin', 'g2-mario-princess', 'g2-mario-bowser'] },
  { id: 'g2-mario-mushroom', name: '蘑菇使', rarity: 'green', art: { type: 'emoji', emoji: '🍄' }, desc: '戴红伞帽的使节，吃了能长个。', flavor: '它递来的蘑菇，红的吃了变大，绿的别碰。', formation: ['g2-mario-star', 'g2-mario-plumber', 'g2-mario-coin', 'g2-mario-princess', 'g2-mario-bowser'] },
  { id: 'g2-mario-coin', name: '金币魂', rarity: 'blue', art: { type: 'emoji', emoji: '🪙' }, desc: '叮当响的金币精灵，跳起来转个圈。', flavor: '它藏在问号块里，等你顶它。', formation: ['g2-mario-star', 'g2-mario-plumber', 'g2-mario-mushroom', 'g2-mario-princess', 'g2-mario-bowser'] },
  { id: 'g2-mario-princess', name: '桃花公主', rarity: 'purple', art: { type: 'emoji', emoji: '👸' }, desc: '住在另一座城堡的公主，总被人请去做客。', flavor: '她被请走的次数比谁都多。', formation: ['g2-mario-star', 'g2-mario-plumber', 'g2-mario-mushroom', 'g2-mario-coin', 'g2-mario-bowser'] },
  { id: 'g2-mario-bowser', name: '龟壳魔王', rarity: 'gold', art: { type: 'emoji', emoji: '🐢' }, desc: '背甲带刺的大乌龟，喷火时最威风。', flavor: '它踩桥的次数比过桥的人还多。', formation: ['g2-mario-star', 'g2-mario-plumber', 'g2-mario-mushroom', 'g2-mario-coin', 'g2-mario-princess'] },
  { id: 'g2-poke-ball', name: '精灵球蛋', rarity: 'white', art: { type: 'egg', colors: ['#fee2e2', '#ef4444'] }, desc: '红白相间的蛋，按一下会弹开。', flavor: '开蛋那声啪，很上头。', formation: ['g2-poke-pika', 'g2-poke-char', 'g2-poke-gym'] },
  { id: 'g2-poke-pika', name: '电鼠', rarity: 'gold', art: { type: 'emoji', emoji: '🐭' }, desc: '两颊带电的仓鼠，放电时脸会鼓。', flavor: '它打架前会先喊自己的名字。', formation: ['g2-poke-ball', 'g2-poke-char', 'g2-poke-gym'] },
  { id: 'g2-poke-char', name: '喷火龙', rarity: 'red', art: { type: 'emoji', emoji: '🐲' }, desc: '尾巴带火苗的爬虫，进化到顶会飞。', flavor: '它不太想回到球里去。', formation: ['g2-poke-ball', 'g2-poke-pika', 'g2-poke-gym'] },
  { id: 'g2-poke-gym', name: '道馆主', rarity: 'blue', art: { type: 'emoji', emoji: '🥇' }, desc: '守着八座场馆之一的馆主，赢了才给徽章。', flavor: '它每天就等一个挑战者。', formation: ['g2-poke-ball', 'g2-poke-pika', 'g2-poke-char'] },
  { id: 'g2-zeld-link', name: '绿衣勇者', rarity: 'green', art: { type: 'emoji', emoji: '🗡️' }, desc: '戴尖帽背小盾的矮个子，睡醒就出发。', flavor: '他睡了一百年，还是那么高。', formation: ['g2-zeld-triforce', 'g2-zeld-master', 'g2-zeld-ganon'] },
  { id: 'g2-zeld-triforce', name: '三角之力', rarity: 'gold', art: { type: 'emoji', emoji: '🔺' }, desc: '三块金三角，力量勇气智慧各归各。', flavor: '它分家的时候吵得可凶了。', formation: ['g2-zeld-link', 'g2-zeld-master', 'g2-zeld-ganon'] },
  { id: 'g2-zeld-master', name: '大师剑', rarity: 'purple', art: { type: 'emoji', emoji: '⚔️' }, desc: '插在石林里的神剑，拔它要先够资格。', flavor: '它睡着的时候连蟋蟀都叫不醒。', formation: ['g2-zeld-link', 'g2-zeld-triforce', 'g2-zeld-ganon'] },
  { id: 'g2-zeld-ganon', name: '灾厄魔王', rarity: 'black', art: { type: 'emoji', emoji: '🐗' }, desc: '等了一百年的野猪魔王，卷土重来。', flavor: '它的计划每次都被一个睡着的人打乱。', formation: ['g2-zeld-link', 'g2-zeld-triforce', 'g2-zeld-master'] },
  { id: 'g2-mc-block', name: '方块蛋', rarity: 'white', art: { type: 'egg', colors: ['#a7f3d0', '#34d399'] }, desc: '浑身棱角的蛋，找不到一条弧线。', flavor: '它滚起来一格一格地滚。', formation: ['g2-mc-creeper', 'g2-mc-steve', 'g2-mc-enderman', 'g2-mc-diamond', 'g2-mc-villager'] },
  { id: 'g2-mc-creeper', name: '嘶嘶怪', rarity: 'red', art: { type: 'emoji', emoji: '💚' }, desc: '绿皮的炸毛怪，一靠近就嘶嘶响。', flavor: '它爆炸前总会好心提醒你。', formation: ['g2-mc-block', 'g2-mc-steve', 'g2-mc-enderman', 'g2-mc-diamond', 'g2-mc-villager'] },
  { id: 'g2-mc-steve', name: '方块匠人', rarity: 'blue', art: { type: 'emoji', emoji: '🧱' }, desc: '徒手拆山的匠人，一晚上一座城。', flavor: '他的名言：先挖个洞。', formation: ['g2-mc-block', 'g2-mc-creeper', 'g2-mc-enderman', 'g2-mc-diamond', 'g2-mc-villager'] },
  { id: 'g2-mc-enderman', name: '瞬移者', rarity: 'purple', art: { type: 'emoji', emoji: '👁️' }, desc: '浑身漆黑眼放紫光的怪，一对视就瞬移。', flavor: '它最怕水和南瓜头。', formation: ['g2-mc-block', 'g2-mc-creeper', 'g2-mc-steve', 'g2-mc-diamond', 'g2-mc-villager'] },
  { id: 'g2-mc-diamond', name: '钻石矿主', rarity: 'gold', art: { type: 'emoji', emoji: '💠' }, desc: '挖矿挖到地心的大矿主，指环都带钻石。', flavor: '它的钻石镐从不离身。', formation: ['g2-mc-block', 'g2-mc-creeper', 'g2-mc-steve', 'g2-mc-enderman', 'g2-mc-villager'] },
  { id: 'g2-mc-villager', name: '交易村民', rarity: 'green', art: { type: 'emoji', emoji: '🧑‍🌾' }, desc: '会跟你换东西的村民，价格永远贵一块。', flavor: '他的哞哞声翻译过来是不二价。', formation: ['g2-mc-block', 'g2-mc-creeper', 'g2-mc-steve', 'g2-mc-enderman', 'g2-mc-diamond'] },
  { id: 'g2-wow-illidan', name: '双刀猎手', rarity: 'black', art: { type: 'emoji', emoji: '🥷' }, desc: '眼角反光的精灵猎手，双刀冒着绿火。', flavor: '他还没准备好。', formation: ['g2-wow-arthas', 'g2-wow-titan', 'g2-wow-guldan'] },
  { id: 'g2-wow-arthas', name: '霜哀之主', rarity: 'black', art: { type: 'emoji', emoji: '🥶' }, desc: '扛着冰剑的王子，剑鞘结了霜。', flavor: '他做的事都值得。', formation: ['g2-wow-illidan', 'g2-wow-titan', 'g2-wow-guldan'] },
  { id: 'g2-wow-titan', name: '泰坦', rarity: 'gold', art: { type: 'emoji', emoji: '🏛️' }, desc: '造了世界又后悔的大个子，在神殿里叹气。', flavor: '它的图纸改过整个军团。', formation: ['g2-wow-illidan', 'g2-wow-arthas', 'g2-wow-guldan'] },
  { id: 'g2-wow-guldan', name: '暗影术士', rarity: 'purple', art: { type: 'emoji', emoji: '🟣' }, desc: '献祭了故乡的术士，只剩一团影子。', flavor: '他的法术书第一页是空白的。', formation: ['g2-wow-illidan', 'g2-wow-arthas', 'g2-wow-titan'] },
  { id: 'g2-sc-zerg', name: '虫群之母', rarity: 'red', art: { type: 'emoji', emoji: '🐜' }, desc: '指挥虫海的女王，一声令下铺天盖地。', flavor: '她数自己孩子从来不用数。', formation: ['g2-sc-protoss', 'g2-sc-marine', 'g2-sc-ultra'] },
  { id: 'g2-sc-protoss', name: '星灵圣堂', rarity: 'gold', art: { type: 'emoji', emoji: '🧠' }, desc: '金光护体的先知，一道光柱灭一队。', flavor: '他开传送门比开门还勤。', formation: ['g2-sc-zerg', 'g2-sc-marine', 'g2-sc-ultra'] },
  { id: 'g2-sc-marine', name: '陆战队员', rarity: 'blue', art: { type: 'emoji', emoji: '👨‍🚀' }, desc: '穿机甲扛步枪的兵，扫描滴答作响。', flavor: '他的咖啡罐是弹壳做的。', formation: ['g2-sc-zerg', 'g2-sc-protoss', 'g2-sc-ultra'] },
  { id: 'g2-sc-ultra', name: '雷兽', rarity: 'red', art: { type: 'emoji', emoji: '🦏' }, desc: '撞碎城墙的巨兽，角比攻城锤粗。', flavor: '它冲锋的时候地都在抖。', formation: ['g2-sc-zerg', 'g2-sc-protoss', 'g2-sc-marine'] },
  { id: 'g2-lol-garen', name: '德玛西亚之剑', rarity: 'green', art: { type: 'emoji', emoji: '🛡️' }, desc: '举着大剑转圈圈的骑士，永远正派。', flavor: '他的宿敌是他自己。', formation: ['g2-lol-teemo', 'g2-lol-blind', 'g2-lol-wind', 'g2-lol-ice', 'g2-lol-wolf'] },
  { id: 'g2-lol-teemo', name: '蘑菇斥候', rarity: 'green', art: { type: 'emoji', emoji: '😈' }, desc: '种蘑菇的小矮子，走两步种一个。', flavor: '踩到蘑菇的都知道他有多阴。', formation: ['g2-lol-garen', 'g2-lol-blind', 'g2-lol-wind', 'g2-lol-ice', 'g2-lol-wolf'] },
  { id: 'g2-lol-blind', name: '盲僧', rarity: 'purple', art: { type: 'emoji', emoji: '🥋' }, desc: '蒙着眼踢腿的武僧，靠回音打架。', flavor: '他踢那一脚之前会念四个字。', formation: ['g2-lol-garen', 'g2-lol-teemo', 'g2-lol-wind', 'g2-lol-ice', 'g2-lol-wolf'] },
  { id: 'g2-lol-wind', name: '御风剑客', rarity: 'gold', art: { type: 'emoji', emoji: '🌬️' }, desc: '背剑说骚话的浪人，风越大他越浪。', flavor: '他的口诀只有一句，来来回回。', formation: ['g2-lol-garen', 'g2-lol-teemo', 'g2-lol-blind', 'g2-lol-ice', 'g2-lol-wolf'] },
  { id: 'g2-lol-ice', name: '冰川箭手', rarity: 'blue', art: { type: 'emoji', emoji: '🏹' }, desc: '冰弓冰箭的女射手，一箭一个减速。', flavor: '她的平A自带雪花特效。', formation: ['g2-lol-garen', 'g2-lol-teemo', 'g2-lol-blind', 'g2-lol-wind', 'g2-lol-wolf'] },
  { id: 'g2-lol-wolf', name: '狼灵', rarity: 'red', art: { type: 'emoji', emoji: '🐺' }, desc: '披着狼皮的猎人，走到哪拆到哪。', flavor: '他的图腾柱比狼还多。', formation: ['g2-lol-garen', 'g2-lol-teemo', 'g2-lol-blind', 'g2-lol-wind', 'g2-lol-ice'] },
  { id: 'g2-dota-shadow', name: '影魔', rarity: 'black', art: { type: 'emoji', emoji: '🖤' }, desc: '浑身黑影的恶魔，大招是吸魂合唱。', flavor: '他放大的时候满屏都是他。', formation: ['g2-dota-pudge'] },
  { id: 'g2-dota-pudge', name: '屠夫', rarity: 'red', art: { type: 'emoji', emoji: '🔪' }, desc: '拎着钩子的胖子，见人就勾。', flavor: '他勾中人的那一下会舔舌头。', formation: ['g2-dota-shadow'] },
  { id: 'g2-cs-defuse', name: '拆弹专家', rarity: 'blue', art: { type: 'emoji', emoji: '🧨' }, desc: '背着钳子的拆弹手，喊一句掩护就上。', flavor: '他拆过的炸弹够填一个坑。', formation: ['g2-cs-terror'] },
  { id: 'g2-cs-terror', name: '匪徒', rarity: 'red', art: { type: 'emoji', emoji: '🦹' }, desc: '蒙面持枪的劫匪，开局抢银行。', flavor: '他的名言：这把稳了。', formation: ['g2-cs-defuse'] },
  { id: 'g2-ow-egg', name: '星云蛋', rarity: 'white', art: { type: 'egg', colors: ['#ede9fe', '#8b5cf6'] }, desc: '裹着星云纹的蛋，隔着壳能看见里面的银河。', flavor: '它裂开的那一瞬，太阳刚好熄了。', formation: ['g2-ow-suit', 'g2-ow-ship', 'g2-ow-nomai', 'g2-ow-star'] },
  { id: 'g2-ow-suit', name: '宇航员', rarity: 'green', art: { type: 'emoji', emoji: '🧑‍🚀' }, desc: '扛着探测器的宇航员，见啥先扫描再说。', flavor: '他每二十二分钟就重来一次。', formation: ['g2-ow-egg', 'g2-ow-ship', 'g2-ow-nomai', 'g2-ow-star'] },
  { id: 'g2-ow-ship', name: '木船', rarity: 'blue', art: { type: 'emoji', emoji: '🚀' }, desc: '用胶带和木头糊的小飞船，飞太快会散架。', flavor: '它起飞全靠一根点火绳。', formation: ['g2-ow-egg', 'g2-ow-suit', 'g2-ow-nomai', 'g2-ow-star'] },
  { id: 'g2-ow-nomai', name: '异乡遗族', rarity: 'gold', art: { type: 'emoji', emoji: '👽' }, desc: '留下满坑文明遗迹的远行种族，便条贴了一星球。', flavor: '他们写的每个箭头都指向同一个地方。', formation: ['g2-ow-egg', 'g2-ow-suit', 'g2-ow-ship', 'g2-ow-star'] },
  { id: 'g2-ow-star', name: '准时爆炸的太阳', rarity: 'red', art: { type: 'emoji', emoji: '🔆' }, desc: '每天准点炸一次的老实太阳。', flavor: '炸完第二天照常上班。', formation: ['g2-ow-egg', 'g2-ow-suit', 'g2-ow-ship', 'g2-ow-nomai'] },
  { id: 'g2-sekiro-wolf', name: '独臂之狼', rarity: 'red', art: { type: 'emoji', emoji: '🥷' }, desc: '断了一臂的忍者，借了把义手刀。', flavor: '他弹开对方刀的那一声，对手会愣一下。', formation: ['g2-sekiro-isshin', 'g2-sekiro-owl', 'g2-sekiro-mortal'] },
  { id: 'g2-sekiro-isshin', name: '苇名剑圣', rarity: 'black', art: { type: 'emoji', emoji: '🦅' }, desc: '守在山顶的老剑客，一根芦苇就能杀人。', flavor: '他的剑快得只能看见出鞘。', formation: ['g2-sekiro-wolf', 'g2-sekiro-owl', 'g2-sekiro-mortal'] },
  { id: 'g2-sekiro-owl', name: '义父', rarity: 'purple', art: { type: 'emoji', emoji: '🎭' }, desc: '面具下的老忍者，教了徒弟再捅徒弟。', flavor: '他的信条：忍无可忍。', formation: ['g2-sekiro-wolf', 'g2-sekiro-isshin', 'g2-sekiro-mortal'] },
  { id: 'g2-sekiro-mortal', name: '不死斩', rarity: 'gold', art: { type: 'emoji', emoji: '🗡️' }, desc: '专门砍不死者的刀，刀身通红。', flavor: '被它砍的人连灰都不留。', formation: ['g2-sekiro-wolf', 'g2-sekiro-isshin', 'g2-sekiro-owl'] },
  { id: 'g2-elden-tarnished', name: '褪色者', rarity: 'purple', art: { type: 'emoji', emoji: '🎖️' }, desc: '灰烬里爬起来的无名者，死了也要骑马回来。', flavor: '他的马是灵魂，比他还倔。', formation: ['g2-elden-tree', 'g2-elden-malenia', 'g2-elden-marika'] },
  { id: 'g2-elden-tree', name: '黄金树', rarity: 'gold', art: { type: 'emoji', emoji: '🍂' }, desc: '罩住整片大陆的巨树，树皮流金。', flavor: '它落下的叶子能换命。', formation: ['g2-elden-tarnished', 'g2-elden-malenia', 'g2-elden-marika'] },
  { id: 'g2-elden-malenia', name: '猩红之剑', rarity: 'red', art: { type: 'emoji', emoji: '🌸' }, desc: '红发女剑客，挥剑时花开满地。', flavor: '她败过一次，就一直等那场雨。', formation: ['g2-elden-tarnished', 'g2-elden-tree', 'g2-elden-marika'] },
  { id: 'g2-elden-marika', name: '黄金律法', rarity: 'black', art: { type: 'emoji', emoji: '💫' }, desc: '定下生死规则的远古存在，是写律法的那支笔。', flavor: '它不允许任何人修改。', formation: ['g2-elden-tarnished', 'g2-elden-tree', 'g2-elden-malenia'] },
  { id: 'g2-witcher-geralt', name: '白狼猎魔人', rarity: 'gold', art: { type: 'emoji', emoji: '🤺' }, desc: '银发双剑的猎魔人，专治各种邪祟。', flavor: '他的狼头徽章会自己动。', formation: ['g2-witcher-silver', 'g2-witcher-gwent', 'g2-witcher-ciri'] },
  { id: 'g2-witcher-silver', name: '银剑', rarity: 'purple', art: { type: 'emoji', emoji: '🔱' }, desc: '涂了银粉的剑，专砍怪物不砍人。', flavor: '砍人用铁剑，砍妖用银剑。', formation: ['g2-witcher-geralt', 'g2-witcher-gwent', 'g2-witcher-ciri'] },
  { id: 'g2-witcher-gwent', name: '昆特牌手', rarity: 'green', art: { type: 'emoji', emoji: '🃏' }, desc: '逢人就要打牌的老赌棍，赢牌比赢仗高兴。', flavor: '他把大魔王的牌赢走了。', formation: ['g2-witcher-geralt', 'g2-witcher-silver', 'g2-witcher-ciri'] },
  { id: 'g2-witcher-ciri', name: '时空之女', rarity: 'red', art: { type: 'emoji', emoji: '⏳' }, desc: '能在时间线里乱窜的女孩，每次回来都换发型。', flavor: '她的朋友每隔一阵就不认识她。', formation: ['g2-witcher-geralt', 'g2-witcher-silver', 'g2-witcher-gwent'] },
  { id: 'g2-diablo-lord', name: '烈焰魔王', rarity: 'black', art: { type: 'emoji', emoji: '👿' }, desc: '从地底爬出来的火焰魔王，三头六臂。', flavor: '它最喜欢听史诗级掉落。', formation: ['g2-diablo-nephalem', 'g2-diablo-tristram'] },
  { id: 'g2-diablo-nephalem', name: '奈非天', rarity: 'red', art: { type: 'emoji', emoji: '👊' }, desc: '天使与恶魔混血的后裔，一拳一个深渊怪。', flavor: '他打出来的装备会发光。', formation: ['g2-diablo-lord', 'g2-diablo-tristram'] },
  { id: 'g2-diablo-tristram', name: '崔斯特瑞姆', rarity: 'purple', art: { type: 'emoji', emoji: '🏰' }, desc: '守着老教堂的镇民，教堂底下埋着魔王。', flavor: '他们都知道，但都不搬。', formation: ['g2-diablo-lord', 'g2-diablo-nephalem'] },
  { id: 'g2-hollow-knight', name: '苍白骑士', rarity: 'black', art: { type: 'emoji', emoji: '⚪' }, desc: '面具下没有脸的苍白骑士，举着骨钉。', flavor: '他的沉默比台词更有力。', formation: ['g2-hollow-shade', 'g2-hollow-hornet'] },
  { id: 'g2-hollow-shade', name: '暗影', rarity: 'purple', art: { type: 'emoji', emoji: '🌑' }, desc: '骑士的影子分身，跑得比他快。', flavor: '它其实很黏主人。', formation: ['g2-hollow-knight', 'g2-hollow-hornet'] },
  { id: 'g2-hollow-hornet', name: '守针者', rarity: 'red', art: { type: 'emoji', emoji: '🪡' }, desc: '用针扎虫子跳舞的猎手，身法极快。', flavor: '她扎完会优雅地鞠躬。', formation: ['g2-hollow-knight', 'g2-hollow-shade'] },
  { id: 'g2-terraria-eye', name: '克苏鲁之眼', rarity: 'red', art: { type: 'emoji', emoji: '🔴' }, desc: '夜里瞪你的大眼睛，盯上就不放。', flavor: '它掉落的材料能造大宝剑。', formation: ['g2-terraria-guide', 'g2-terraria-wall'] },
  { id: 'g2-terraria-guide', name: '向导', rarity: 'green', art: { type: 'emoji', emoji: '💬' }, desc: '守着出生点的向导，什么都懂一点。', flavor: '他最大的爱好是给你提示。', formation: ['g2-terraria-eye', 'g2-terraria-wall'] },
  { id: 'g2-terraria-wall', name: '血肉之墙', rarity: 'purple', art: { type: 'emoji', emoji: '🥩' }, desc: '横跨地底的肉墙，打它要先清掉口部。', flavor: '它死的时候整个地底都在哭。', formation: ['g2-terraria-eye', 'g2-terraria-guide'] },
  { id: 'g2-skyrim-dovah', name: '龙裔', rarity: 'red', art: { type: 'emoji', emoji: '🐉' }, desc: '吞了龙魂的战士，喊一嗓子就能吼死龙。', flavor: '他学龙语比学外语快。', formation: ['g2-witcher-geralt', 'g2-witcher-silver'] },
  { id: 'g2-re-umbrella', name: '保护伞', rarity: 'red', art: { type: 'emoji', emoji: '☂️' }, desc: '红白条纹的伞，遮的却不是雨。', flavor: '它打开的时候，城市会安静。', formation: ['g2-re-licker', 'g2-re-raccoon'] },
  { id: 'g2-re-licker', name: '舔食者', rarity: 'red', art: { type: 'emoji', emoji: '👅' }, desc: '没皮没眼的怪，靠舌头找路。', flavor: '它的舌头比你手长。', formation: ['g2-re-umbrella', 'g2-re-raccoon'] },
  { id: 'g2-re-raccoon', name: '浣熊警员', rarity: 'blue', art: { type: 'emoji', emoji: '🦝' }, desc: '留守浣熊市的警察，手电筒常亮。', flavor: '他的搭档是条丧尸犬。', formation: ['g2-re-umbrella', 'g2-re-licker'] },
  { id: 'g2-hl-gordon', name: '撬棍科学家', rarity: 'gold', art: { type: 'emoji', emoji: '🔧' }, desc: '穿着防护服拎撬棍的科学家，见啥撬啥。', flavor: '他的撬棍比枪好用。', formation: ['g2-hl-blackmesa', 'g2-portal-gla', 'g2-portal-cube'] },
  { id: 'g2-hl-blackmesa', name: '黑山基地', rarity: 'purple', art: { type: 'emoji', emoji: '🏭' }, desc: '建在山体里的研究所，实验出了大篓子。', flavor: '电梯永远是坏的。', formation: ['g2-hl-gordon', 'g2-portal-gla', 'g2-portal-cube'] },
  { id: 'g2-portal-gla', name: '光圈核心', rarity: 'gold', art: { type: 'emoji', emoji: '💡' }, desc: '一颗会说话的光球，爱算计爱唱歌。', flavor: '它数到三的时候你别信。', formation: ['g2-hl-gordon', 'g2-hl-blackmesa', 'g2-portal-cube'] },
  { id: 'g2-portal-cube', name: '伴生方块', rarity: 'blue', art: { type: 'emoji', emoji: '📦' }, desc: '被反复利用的方块，一心只想被放在按钮上。', flavor: '它被烤过无数次还乐在其中。', formation: ['g2-hl-gordon', 'g2-hl-blackmesa', 'g2-portal-gla'] },
  { id: 'g2-doom-slayer', name: '毁灭战士', rarity: 'red', art: { type: 'emoji', emoji: '🪓' }, desc: '沉默的枪械狂人，见恶魔就开火。', flavor: '他撕恶魔的样子像拆包装。', formation: ['g2-cs-defuse', 'g2-cs-terror', 'g2-diablo-nephalem'] },
  { id: 'g2-genshin-paimon', name: '应急食品', rarity: 'gold', art: { type: 'emoji', emoji: '🍽️' }, desc: '会飞会说话的小漂浮物，自称向导。', flavor: '它总是第一个喊饿。', formation: ['g2-genshin-anemo', 'g2-genshin-adepti'] },
  { id: 'g2-genshin-anemo', name: '风神', rarity: 'purple', art: { type: 'emoji', emoji: '🍃' }, desc: '拨动竖琴的风之精灵，弹着弹着就刮风。', flavor: '他最大的爱好是喝酒。', formation: ['g2-genshin-paimon', 'g2-genshin-adepti'] },
  { id: 'g2-genshin-adepti', name: '仙人', rarity: 'gold', art: { type: 'emoji', emoji: '🪷' }, desc: '云端下棋的老仙人，一步一个凡间。', flavor: '他批奏折用毛笔蘸云雾。', formation: ['g2-genshin-paimon', 'g2-genshin-anemo'] },
  { id: 'g2-ark-doc', name: '罗德岛博士', rarity: 'purple', art: { type: 'emoji', emoji: '🎩' }, desc: '拄着指挥杖的博士，指挥干员跟下棋似的。', flavor: '他的战术板上全是小方块。', formation: ['g2-ark-ch'] },
  { id: 'g2-ark-ch', name: '整合运动', rarity: 'red', art: { type: 'emoji', emoji: '🏴' }, desc: '戴着面罩的阵营领袖，要推翻那座城。', flavor: '他们的口号比行动响。', formation: ['g2-ark-doc'] },
  { id: 'g2-hsr-train', name: '星穹列车', rarity: 'gold', art: { type: 'emoji', emoji: '🚂' }, desc: '开往星空尽头的列车，乘客都是旅客。', flavor: '它的车票可以换命运。', formation: ['g2-hsr-blazer'] },
  { id: 'g2-hsr-blazer', name: '开拓者', rarity: 'purple', art: { type: 'emoji', emoji: '🧳' }, desc: '拖着行李箱上车的人，每站都下车看看。', flavor: '他的箱子重得像整个世界。', formation: ['g2-hsr-train'] },
  { id: 'g2-sv-farmer', name: '农场主', rarity: 'green', art: { type: 'emoji', emoji: '🚜' }, desc: '继承了爷爷农场的年轻人，从锄地开始。', flavor: '他种的最多的其实是萝卜。', formation: ['g2-sv-junimo'] },
  { id: 'g2-sv-junimo', name: '精灵果农', rarity: 'blue', art: { type: 'emoji', emoji: '🍓' }, desc: '住在果园里的小精灵，帮你收菜。', flavor: '它们收菜时唱歌跑调。', formation: ['g2-sv-farmer'] },
  { id: 'g2-board-dice', name: '骰子蛋', rarity: 'white', art: { type: 'egg', colors: ['#e0e7ff', '#6366f1'] }, desc: '点数会变的蛋，摇一摇换一面。', flavor: '它摇出六的概率总是比别人高。', formation: ['g2-board-werewolf', 'g2-board-sgs', 'g2-board-monopoly', 'g2-board-uno', 'g2-board-queen', 'g2-board-go'] },
  { id: 'g2-board-werewolf', name: '狼人', rarity: 'purple', art: { type: 'emoji', emoji: '🌕' }, desc: '月亮一升就变身的村民，白天装无辜。', flavor: '他每轮都要指认别人。', formation: ['g2-board-dice', 'g2-board-sgs', 'g2-board-monopoly', 'g2-board-uno', 'g2-board-queen', 'g2-board-go'] },
  { id: 'g2-board-sgs', name: '三国杀将', rarity: 'blue', art: { type: 'emoji', emoji: '🀄' }, desc: '拿身份牌互相猜的将领，忠奸难辨。', flavor: '他的主公每次都先挨刀。', formation: ['g2-board-dice', 'g2-board-werewolf', 'g2-board-monopoly', 'g2-board-uno', 'g2-board-queen', 'g2-board-go'] },
  { id: 'g2-board-monopoly', name: '大富翁', rarity: 'gold', art: { type: 'emoji', emoji: '💼' }, desc: '开着豪车收租的地产王，路过就要收过路费。', flavor: '他的骰子灌了铅。', formation: ['g2-board-dice', 'g2-board-werewolf', 'g2-board-sgs', 'g2-board-uno', 'g2-board-queen', 'g2-board-go'] },
  { id: 'g2-board-uno', name: '变色牌', rarity: 'red', art: { type: 'emoji', emoji: '🌈' }, desc: '能变颜色的纸牌，一扔出去全场换色。', flavor: '它最喜欢喊反转。', formation: ['g2-board-dice', 'g2-board-werewolf', 'g2-board-sgs', 'g2-board-monopoly', 'g2-board-queen', 'g2-board-go'] },
  { id: 'g2-board-queen', name: '王后', rarity: 'gold', art: { type: 'emoji', emoji: '♛' }, desc: '棋盘上横冲直撞的王后，没有她到不了的格。', flavor: '她的吃法一条直线通杀。', formation: ['g2-board-dice', 'g2-board-werewolf', 'g2-board-sgs', 'g2-board-monopoly', 'g2-board-uno', 'g2-board-go'] },
  { id: 'g2-board-go', name: '落子神', rarity: 'gold', art: { type: 'emoji', emoji: '⚫' }, desc: '闭眼落子的棋圣，落子无悔。', flavor: '他数棋的时候数两遍，怕数错。', formation: ['g2-board-dice', 'g2-board-werewolf', 'g2-board-sgs', 'g2-board-monopoly', 'g2-board-uno', 'g2-board-queen'] },
  { id: 'g2-game-all', name: '全能玩家', rarity: 'rainbow', art: { type: 'emoji', emoji: '👾' }, desc: '所有游戏的存档都在它的卡带里。', flavor: '它掉线的时候，全世界都会卡一下。', formation: ['g2-crystal-final'] },
  { id: 'g2-crystal-final', name: '最终水晶', rarity: 'rainbow', art: { type: 'emoji', emoji: '💎' }, desc: '所有故事都是为了守护它而展开。', flavor: '它一碎，世界就要重来。', formation: ['g2-game-all'] },
];

CARDS.forEach((c, i) => { c.no = i + 1; });

const CARD_MAP = {};
CARDS.forEach(c => { CARD_MAP[c.id] = c; });

const CONFIG = {
  VERSION: '2.1.2',
  INTERVAL_BASE: 10,
  INTERVAL_EXP: 0.4956,
  MIN_INTERVAL: 0.005,
  OFFLINE_CAP_HOURS: 8,
  FRAG_COST_PER_DRAW: 10,
  MAX_FRAG_DRAWS: 50000,
  SECRET_EGG_RATE: 1e-7,
  HOME_EGG_MIN: 900,
  HOME_EGG_MAX: 7200,
  HOME_EGG_BOOST: 0.5,
  SHINY_RATE: 0.00001,
  SHOP: {
    PITY: {
      purple: { baseCost: 50000, growth: 5 },
      gold: { baseCost: 800000, growth: 5 },
      black: { baseCost: 20000000, growth: 10 },
    },
    NEST_SLOT_COSTS: [100000, 1000000, 10000000],
    COSMETIC_FRAME_COST: 100000000,
  },
  ROGUE: {
    WAVE_TIMEOUT: 10,
    MONSTER_GROWTH: 1.35,
    MONSTER_BASE: 3,
    FRAG_EQUIV_MULT: 3,
    FRAG_WAVE_SECS: 10,
    COIN_BASE: 10,
    COIN_GROWTH: 1.15,
    OPTION_COUNT: 3,
    TEAM_LIMIT: 5,
    CONSUME_MIN: 2,
    UP_POWER_MULT: 1.25,
    WEAK_EVERY: 5,
    WEAK_WINDOW: 1.2,
    REROLL_BASE: 5,
    REROLL_MAX: 3,
    EVENT_CHANCE: 0.18,
    MILESTONE_WAVE: 10,
    MILESTONE_FRAG: 50,
    EVENTS: {
      layer: { name: '流派共鸣', desc: '随机一个流派被动 +1 层', icon: '🌟' },
      gold: { name: '金币礼包', desc: '本局金币大幅增加', icon: '💰' },
      evo: { name: '强行进化', desc: '随机一张队伍卡强化 +3', icon: '🧬' },
    },
    EVO_LV: 3,
    EVO_MULT: 5,
    BOND_GROWTH: 0.05,
    UPGRADES: {
      time: { name: '波次时限', desc: '每波限时 +0.5 秒', max: 50, base: 20, growth: 1.25 },
      damage: { name: '伤害强化', desc: '本局伤害 +2%', max: 50, base: 20, growth: 1.25 },
      crit: { name: '暴击率', desc: '暴击率 +1%', max: 50, base: 20, growth: 1.25 },
      critd: { name: '暴击伤害', desc: '暴击伤害 +5%', max: 50, base: 20, growth: 1.25 },
      weakauto: { name: '弱点直觉', desc: '弱点自动命中 +1%', max: 50, base: 20, growth: 1.25 },
    },
    MECHANICS: {
      growth: { label: '生长', desc: '每层：全队伤害 ×1.44' },
      combo: { label: '连击', desc: '每层：连击链攻击次数期望 ×1.4' },
      crit: { label: '暴击', desc: '每层：暴击伤害 ×1.4，暴击率随层与局外养成提升' },
      smash: { label: '强击', desc: '每层：每 5 秒附加 2×1.5^(层-1) 次重击' },
      raid: { label: '突袭', desc: '每层：开局将怪血量降至 ×0.7' },
      delay: { label: '时延', desc: '每层：限时 +5×1.5^(层-1) 秒' },
      haste: { label: '攻速', desc: '每层：攻击频率 ×1.4' },
      press: { label: '压制', desc: '每层：怪物血量 ×0.71' },
    },
  },
  ACHIEVEMENTS: [
    { id: 'pulls-100', name: '初出茅庐', desc: '累计抽卡 100 次', type: 'pulls', goal: 100, reward: 500 },
    { id: 'pulls-1000', name: '抽卡学徒', desc: '累计抽卡 1 千次', type: 'pulls', goal: 1000, reward: 5000 },
    { id: 'pulls-10000', name: '抽卡大师', desc: '累计抽卡 1 万次', type: 'pulls', goal: 10000, reward: 50000 },
    { id: 'kills-100', name: '猎蛋新手', desc: '累计击杀 100 只怪物', type: 'kills', goal: 100, reward: 500 },
    { id: 'clicks-100', name: '兔拉米拉米比啾豆', desc: '点击小怪兽 100 次', type: 'clicks', goal: 100, reward: 500 },
    { id: 'kills-5000', name: '猎蛋达人', desc: '累计击杀 5 千只怪物', type: 'kills', goal: 5000, reward: 10000 },
    { id: 'kills-50000', name: '猎蛋狂魔', desc: '累计击杀 5 万只怪物', type: 'kills', goal: 50000, reward: 100000 },
    { id: 'owned-20', name: '集卡入门', desc: '拥有 20 种卡片', type: 'owned', goal: 20, reward: 1000 },
    { id: 'owned-60', name: '集卡好手', desc: '拥有 60 种卡片', type: 'owned', goal: 60, reward: 3000 },
    { id: 'owned-100', name: '集卡大师', desc: '拥有 100 种卡片', type: 'owned', goal: 100, reward: 10000 },
    { id: 'owned-all', name: '全图鉴', desc: '拥有全部 ' + CARDS.filter(c => !c.hidden).length + ' 种卡片', type: 'owned', goal: CARDS.filter(c => !c.hidden).length, reward: 50000 },
    { id: 'rarity-purple', name: '紫霞初现', desc: '获得任意一张紫卡', type: 'rarity', goal: 'purple', reward: 1000 },
    { id: 'rarity-gold', name: '金光乍现', desc: '获得任意一张金卡', type: 'rarity', goal: 'gold', reward: 5000 },
    { id: 'rarity-black', name: '深渊凝视', desc: '获得任意一张黑卡', type: 'rarity', goal: 'black', reward: 500000 },
    { id: 'rarity-rainbow', name: '虹彩之巅', desc: '获得任意一张炫彩卡', type: 'rarity', goal: 'rainbow', reward: 1000000 },
    { id: 'power-1e4', name: '战力破万', desc: '当前出战编队战力达到 1 万', type: 'power', goal: 10000, reward: 10000 },
    { id: 'power-1e6', name: '战力百万', desc: '当前出战编队战力达到 100 万', type: 'power', goal: 1000000, reward: 100000 },
    { id: 'frags-10000', name: '碎片富翁', desc: '累计获得 1 万碎片', type: 'frags', goal: 10000, reward: 1000 },
    { id: 'offline-10000', name: '离线暴富', desc: '单次离线收益达到 1 万碎片', type: 'offline', goal: 10000, reward: 2000 },
    { id: 'nest-1', name: '宝宝出生了', desc: '开启第一枚蛋', type: 'nest', goal: 1, reward: 1000 },
    { id: 'rogue-1000', name: '千波霸主', desc: '冒险模式单局突破 1000 波', type: 'rogue', goal: 1000, reward: 5000000 },
    { id: 'secret-egg', name: '幻蛋之秘', desc: '触发神秘的炫彩幻蛋', type: 'secret', goal: 1, reward: 1000000 },
  ],
};
